project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"   # Only render qmd files

format:
  html:
    theme:
      - cosmo
    toc: true
    code-fold: true

  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: EDS 232 - Machine Learning for Environmental Science
  page-footer: 
    left: "This work is licensed under [CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) License](https://creativecommons.org/licenses/by-nc/4.0/)" 
    right: This website is built with [Quarto](https://quarto.org/) and [GitHub pages](https://github.com/MEDS-eds-220/MEDS-eds-220-course).
  
  announcement: 
    icon: hammer
    dismissable: true
    content: "This wesbite is under construction."
    type: primary
    position: below-navbar
    
  navbar:
    right:
      - text: home
        href: index.qmd
      - text: notes
        href: notes/week-by-week/week-by-week.qmd
      - text: assignments
        href: "#"
      - text: weekly labs
        href: "#"
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/MEDS-eds-232/EDS-232-course-website
          - text: Report a bug
            url: https://github.com/MEDS-eds-232/EDS-232-course-website/issues
    
  sidebar:
      - id: notes
        contents:
          - notes/week-by-week/week-by-week.qmd
          - notes/setup/setup.qmd
          - section: 'Introduction'
            contents:
              - notes/1_0_what_is_machine_learning/1_0_what_is_machine_learning-NOTES.qmd
              - notes/2_1_what_is_statistical_learning/2_1_what_is_statistical_learning-NOTES.qmd
              - notes/2_2_assessing_model_accuracy/2_2_assessing_model_accuracy-NOTES.qmd
          - section : 'Linear regression'
            contents:
              - notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.qmd

link-external-newwindow: True

bibliography: references/references.bib