<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Simple linear regression – EDS 232 - Machine Learning for Environmental Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 232 - Machine Learning for Environmental Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../notes/week-by-week/week-by-week.html" aria-current="page"> 
<span class="menu-text">notes</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/MEDS-eds-232/EDS-232-course-website">
 <span class="dropdown-text">Source code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/MEDS-eds-232/EDS-232-course-website/issues">
 <span class="dropdown-text">Report a bug</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html">Linear regression</a></li><li class="breadcrumb-item"><a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html">Simple linear regression</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
  <div id="quarto-announcement" data-announcement-id="c7b7782e967bb59a093245536bfed491" class="alert alert-primary hidden"><i class="bi bi-hammer quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p>This wesbite is under construction.</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/week-by-week/week-by-week.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week by week</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/setup/setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setup</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/1_0_what_is_machine_learning/1_0_what_is_machine_learning-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is machine learning?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/2_1_what_is_statistical_learning/2_1_what_is_statistical_learning-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning from data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/2_2_assessing_model_accuracy/2_2_assessing_model_accuracy-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Training and test errors, and model flexibility</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Simple linear regression</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivating-questions" id="toc-motivating-questions" class="nav-link active" data-scroll-target="#motivating-questions">Motivating questions</a></li>
  <li><a href="#a-guiding-example-the-greenabate-dataset" id="toc-a-guiding-example-the-greenabate-dataset" class="nav-link" data-scroll-target="#a-guiding-example-the-greenabate-dataset">A guiding example: the GreenAbate dataset</a></li>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link" data-scroll-target="#simple-linear-regression">Simple linear regression</a></li>
  <li><a href="#estimating-the-coefficients" id="toc-estimating-the-coefficients" class="nav-link" data-scroll-target="#estimating-the-coefficients">Estimating the coefficients</a>
  <ul class="collapse">
  <li><a href="#residuals-and-residual-sum-of-squares-rss" id="toc-residuals-and-residual-sum-of-squares-rss" class="nav-link" data-scroll-target="#residuals-and-residual-sum-of-squares-rss">Residuals and Residual sum of squares (RSS)</a></li>
  </ul></li>
  <li><a href="#accuracy-of-the-coefficient-estimates" id="toc-accuracy-of-the-coefficient-estimates" class="nav-link" data-scroll-target="#accuracy-of-the-coefficient-estimates">Accuracy of the coefficient estimates</a>
  <ul class="collapse">
  <li><a href="#standard-errors" id="toc-standard-errors" class="nav-link" data-scroll-target="#standard-errors">Standard errors</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">Confidence intervals</a></li>
  </ul></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis testing</a>
  <ul class="collapse">
  <li><a href="#the-null-and-alternative-hypothesis" id="toc-the-null-and-alternative-hypothesis" class="nav-link" data-scroll-target="#the-null-and-alternative-hypothesis">The null and alternative hypothesis</a></li>
  <li><a href="#the-t-statistic-p-values" id="toc-the-t-statistic-p-values" class="nav-link" data-scroll-target="#the-t-statistic-p-values">The <span class="math inline">\(t\)</span>-statistic &amp; <span class="math inline">\(p\)</span>-values</a></li>
  </ul></li>
  <li><a href="#assessing-model-accuracy" id="toc-assessing-model-accuracy" class="nav-link" data-scroll-target="#assessing-model-accuracy">Assessing model accuracy</a>
  <ul class="collapse">
  <li><a href="#residual-standard-error-rse" id="toc-residual-standard-error-rse" class="nav-link" data-scroll-target="#residual-standard-error-rse">Residual Standard Error (RSE)</a></li>
  <li><a href="#r2-statistic" id="toc-r2-statistic" class="nav-link" data-scroll-target="#r2-statistic"><span class="math inline">\(R^2\)</span> statistic</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html">Linear regression</a></li><li class="breadcrumb-item"><a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html">Simple linear regression</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Simple linear regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div id="e4fc8525" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">'default'</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>fig_size_x <span class="op">=</span> <span class="dv">8</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>fig_size_y <span class="op">=</span> <span class="dv">4</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">'font.size'</span>] <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># ── GreenAbate synthetic dataset ───────────────────────────────────────────────────────</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 200 manufacturing firms tracked on three abatement spending channels and</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># their resulting annual CO₂ emissions reduction.</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Predictors (annual spending, $K):</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">#   process    – investment in cleaner production processes        (≈ TV)</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="co">#   efficiency – energy efficiency upgrades                        (≈ radio)</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">#   offsets    – carbon offset purchases                           (≈ newspaper)</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Response:</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co">#   co2_reduction – annual CO₂ emissions reduced (thousand metric tons, ktCO₂e)</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co"># True data-generating model (mirrors ISLP Advertising, Ch. 3):</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="co">#   co2_reduction = 2.939 + 0.046·process + 0.189·efficiency − 0.001·offsets + ε</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co">#   ε ~ N(0, 1.69²)</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># ─────────────────────────────────────────────────────────────────────────────</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">7</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>process    <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">300</span>, n)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>efficiency <span class="op">=</span> np.random.uniform(<span class="dv">0</span>,  <span class="dv">50</span>, n)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>offsets    <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="dv">100</span>, n)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>co2_reduction <span class="op">=</span> (<span class="fl">2.939</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>                 <span class="op">+</span> <span class="fl">0.046</span>  <span class="op">*</span> process</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>                 <span class="op">+</span> <span class="fl">0.189</span>  <span class="op">*</span> efficiency</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>                 <span class="op">-</span> <span class="fl">0.001</span>  <span class="op">*</span> offsets</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>                 <span class="op">+</span> np.random.normal(<span class="dv">0</span>, <span class="fl">1.69</span>, n))</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    <span class="st">'process'</span>:       process,</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>    <span class="st">'efficiency'</span>:    efficiency,</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>    <span class="st">'offsets'</span>:       offsets,</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>    <span class="st">'co2_reduction'</span>: co2_reduction</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>In this lesson we introduce:</p>
<ul>
<li>The simple linear regression (SLR) model and its assumptions</li>
<li>How the model coefficients are estimated (least squares)</li>
<li>How to assess the accuracy of the coefficient estimates (standard errors, confidence intervals)</li>
<li>How to test whether a relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> exists (hypothesis testing, <span class="math inline">\(t\)</span>-statistic, <span class="math inline">\(p\)</span>-values)</li>
<li>How to assess overall model accuracy (RSE and <span class="math inline">\(R^2\)</span>)</li>
</ul>
<p>These notes are based on chapter 3.1 of <em>An Introduction to Statistical Learning with Applications in Python</em> <span class="citation" data-cites="islp_2023">(<a href="#ref-islp_2023" role="doc-biblioref">James et al. 2023</a>)</span>. The <strong>example data is synthetic</strong> and was generated with the aid of Claude Code for the purpose of this lesson based on the data in ISLP used in Figure 2.1.</p>
<section id="motivating-questions" class="level2">
<h2 class="anchored" data-anchor-id="motivating-questions">Motivating questions</h2>
<p>Regression is a method for estimating and studying the relationship between one or more predictors and a response variable. It allows us to investigate answers to questions such as:</p>
<ol type="1">
<li>Is there a relationship between the predictor(s) and the response?</li>
<li>How strong is that relationship?</li>
<li>Which predictors are actually associated with the response?</li>
<li>How large is the effect of each predictor on the response?</li>
<li>Is the relationship linear?</li>
<li>How accurately can we predict the response for a given combination of predictor values?</li>
</ol>
<p>We do not need to answer all of these at once. We can select the questions that matter most for our specific goal, depending on whether we are doing <strong>inference</strong> or <strong>prediction</strong>.</p>
<p><strong>Linear regression</strong> can be really useful for addressing all of these questions. Unlike more flexible methods that may prioritize prediction accuracy, linear regression supports direct inference: you can interpret the coefficients, compute confidence intervals, and test hypotheses about the relationship between variables.</p>
</section>
<section id="a-guiding-example-the-greenabate-dataset" class="level2">
<h2 class="anchored" data-anchor-id="a-guiding-example-the-greenabate-dataset">A guiding example: the GreenAbate dataset</h2>
<p>A research consortium tracks <strong>200 manufacturing firms</strong> across different industries and regions. For each firm they record annual spending on three emissions-reduction strategies and the resulting CO₂ savings:</p>
<ul>
<li><strong><code>process</code></strong> — investment in cleaner production processes ($K/year)</li>
<li><strong><code>efficiency</code></strong> — energy efficiency upgrades ($K/year)</li>
<li><strong><code>offsets</code></strong> — carbon offset purchases ($K/year)</li>
<li><strong><code>co2_reduction</code></strong> — annual CO₂ emissions reduced (thousand metric tons, ktCO₂e)</li>
</ul>
<p>The central question is: <em>do these investments actually drive emissions reductions, and if so, by how much?</em></p>
<p>The figure below shows <code>co2_reduction</code> plotted against each predictor separately.</p>
<div id="cell-initial-data-plotting" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(fig_size_x, fig_size_y <span class="op">*</span> <span class="dv">3</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>specs <span class="op">=</span> [</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'process'</span>,    <span class="st">'steelblue'</span>,  <span class="st">'Process upgrades ($K)'</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'efficiency'</span>, <span class="st">'darkorange'</span>, <span class="st">'Efficiency upgrades ($K)'</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    (<span class="st">'offsets'</span>,    <span class="st">'seagreen'</span>,   <span class="st">'Carbon offsets ($K)'</span>),</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (col, color, xlabel) <span class="kw">in</span> <span class="bu">zip</span>(axes, specs):</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    ax.scatter(df[col], df[<span class="st">'co2_reduction'</span>], s<span class="op">=</span><span class="dv">15</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span>color)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(xlabel)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">'CO₂ reduction (ktCO₂e)'</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>fig.suptitle(</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">'GreenAbate dataset – CO₂ reduction vs. each abatement channel</span><span class="ch">\n</span><span class="st">'</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'*Synthetic data generated for educational purposes only*'</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    y<span class="op">=</span><span class="fl">1.01</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="3_1_simple_linear_regression-NOTES_files/figure-html/initial-data-plotting-output-1.png" id="initial-data-plotting" width="789" height="1217" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can see the <code>process</code> spending shows the strongest linear association with CO₂ reductions; <code>efficiency</code> spending shows a moderate relationship; <code>offsets</code> shows a weak one. In this lesson we focus on <strong>simple linear regression</strong> (one predictor at a time), using <code>process</code> as our primary example. We will bring in all three predictors in the next lesson on multiple linear regression.</p>
</section>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple linear regression</h2>
<p><strong>Simple linear regression (SLR)</strong> assumes a (roughly) linear relationship between a single predictor <span class="math inline">\(X\)</span> and a response <span class="math inline">\(Y\)</span>. The model is given by</p>
<p><span class="math display">\[Y \approx \beta_0 + \beta_1 X\]</span></p>
<p>where</p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> is the <strong>y-intercept</strong>: the value of <span class="math inline">\(Y\)</span> when <span class="math inline">\(X = 0\)</span>,</li>
<li><span class="math inline">\(\beta_1\)</span> is the <strong>slope</strong>: the average change in <span class="math inline">\(Y\)</span> for a one-unit increase in <span class="math inline">\(X\)</span>.</li>
</ul>
<p>Together, <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are the model <strong>coefficients</strong> (also called <strong>parameters</strong>). They define the true underlying function <span class="math inline">\(f\)</span> that maps <span class="math inline">\(X\)</span> to <span class="math inline">\(Y\)</span>.</p>
<p>In practice, we do not know the true <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, so we <strong>estimate</strong> them from data. Given estimates <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>, our prediction for <span class="math inline">\(Y\)</span> at a value <span class="math inline">\(x\)</span> is</p>
<p><span class="math display">\[\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x = \hat{f}(x).\]</span></p>
<p>Remember the “hat” notation (<span class="math inline">\(\hat{\ }\)</span>) throughout these notes indicates an <strong>estimated</strong> quantity, not the true, unknown population value.</p>
<p>For the GreenAbate dataset, using <code>process</code> as the sole predictor, SLR models CO₂ reductions as</p>
<p><span class="math display">\[\texttt{co2\_reduction} \approx \hat{\beta}_0 + \hat{\beta}_1 \cdot \texttt{process}\]</span></p>
<div id="e9a5c39a" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>model_proc <span class="op">=</span> LinearRegression().fit(df[[<span class="st">'process'</span>]], df[<span class="st">'co2_reduction'</span>])</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>b0 <span class="op">=</span> model_proc.intercept_</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>b1 <span class="op">=</span> model_proc.coef_[<span class="dv">0</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>x_line <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">300</span>, <span class="dv">300</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># statsmodels fit (needed for SEs, CIs, p-values throughout)</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>X_ols <span class="op">=</span> sm.add_constant(df[<span class="st">'process'</span>])</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>res   <span class="op">=</span> sm.OLS(df[<span class="st">'co2_reduction'</span>], X_ols).fit()</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(fig_size_x, fig_size_y))</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>plt.scatter(df[<span class="st">'process'</span>], df[<span class="st">'co2_reduction'</span>], s<span class="op">=</span><span class="dv">20</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, color<span class="op">=</span><span class="st">'steelblue'</span>, label<span class="op">=</span><span class="st">'Observed data'</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>plt.plot(x_line, b0 <span class="op">+</span> b1 <span class="op">*</span> x_line, <span class="st">'b-'</span>, linewidth<span class="op">=</span><span class="fl">2.5</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="ss">f'Fitted line: $</span><span class="ch">\\</span><span class="ss">hat</span><span class="ch">{{</span><span class="ss">y</span><span class="ch">}}</span><span class="ss"> = </span><span class="sc">{</span>b0<span class="sc">:.2f}</span><span class="ss"> + </span><span class="sc">{</span>b1<span class="sc">:.4f}</span><span class="ch">\\</span><span class="ss">,x$'</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Process upgrade spending ($K)'</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'CO₂ reduction (ktCO₂e)'</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="3_1_simple_linear_regression-NOTES_files/figure-html/cell-4-output-1.png" width="789" height="390" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>In the context of this problem, what does <span class="math inline">\(\hat{\beta}_0\)</span> represent?</li>
<li>What does <span class="math inline">\(\hat{\beta}_1\)</span> represent?</li>
<li>If a firm spends $150K on process upgrades, what is the model’s predicted CO₂ reduction?</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(\hat{\beta}_0\)</span> is the <strong>intercept</strong>: the model’s predicted CO₂ reduction for a firm that spends $0 on process upgrades. In practice this baseline reflects reductions driven by factors other than process spending that are not captured in the model.</li>
<li><span class="math inline">\(\hat{\beta}_1\)</span> is the <strong>slope</strong>: the average increase in CO₂ reduction (in ktCO₂e) associated with each additional $1K spent on process upgrades. A positive <span class="math inline">\(\hat{\beta}_1\)</span> means that higher process investment is associated with greater reductions.</li>
<li>At <span class="math inline">\(x = 150\)</span> we have that <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 \cdot 150\)</span>. With the fitted values from the model this gives approximately 14.59 ktCO₂e.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="estimating-the-coefficients" class="level2">
<h2 class="anchored" data-anchor-id="estimating-the-coefficients">Estimating the coefficients</h2>
<section id="residuals-and-residual-sum-of-squares-rss" class="level3">
<h3 class="anchored" data-anchor-id="residuals-and-residual-sum-of-squares-rss">Residuals and Residual sum of squares (RSS)</h3>
<p>Given <span class="math inline">\(n\)</span> training observations <span class="math inline">\((x_1, y_1), \ldots, (x_n, y_n)\)</span>, we want to find <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> such that the line <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x\)</span> is as close as possible to the observed data. For this, we need to define what does “as close as possible” mean mathematically.</p>
<p>In our previous lesson we had talked about the <strong>residual</strong> for observation <span class="math inline">\(i\)</span> being the difference between the observed response and the predicted response:</p>
<p><span class="math display">\[y_i - \hat{y}_i = y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i.\]</span></p>
<p>The <strong>residual sum of squares (RSS)</strong> totals the squared residuals across all observations:</p>
<p><span class="math display">\[RSS = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = \sum_{i=1}^{n} (y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i)^2.\]</span></p>
<p>The <strong>least squares</strong> approach to fit the regression line chooses <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> to <strong>minimize</strong> the RSS. The residuals are shown as vertical segments below:</p>
<div id="cell-residuals" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(fig_size_x, fig_size_y))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>plt.scatter(df[<span class="st">'process'</span>], df[<span class="st">'co2_reduction'</span>], s<span class="op">=</span><span class="dv">15</span>, alpha<span class="op">=</span><span class="fl">0.4</span>, color<span class="op">=</span><span class="st">'steelblue'</span>, zorder<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="st">'Observed data'</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>plt.plot(x_line, b0 <span class="op">+</span> b1 <span class="op">*</span> x_line, <span class="st">'b-'</span>, linewidth<span class="op">=</span><span class="fl">2.5</span>, zorder<span class="op">=</span><span class="dv">3</span>, label<span class="op">=</span><span class="st">'Fitted line'</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, (xi, yi) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(df[<span class="st">'process'</span>], df[<span class="st">'co2_reduction'</span>])):</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    yi_hat <span class="op">=</span> b0 <span class="op">+</span> b1 <span class="op">*</span> xi</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    lbl <span class="op">=</span> <span class="st">'Residual $e_i = y_i - </span><span class="ch">\\</span><span class="st">hat</span><span class="sc">{y}</span><span class="st">_i$'</span> <span class="cf">if</span> i <span class="op">==</span> <span class="dv">0</span> <span class="cf">else</span> <span class="va">None</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    plt.plot([xi, xi], [yi, yi_hat], color<span class="op">=</span><span class="st">'tomato'</span>, linewidth<span class="op">=</span><span class="fl">0.6</span>, alpha<span class="op">=</span><span class="fl">0.6</span>, label<span class="op">=</span>lbl, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Process upgrade spending ($K)'</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'CO₂ reduction (ktCO₂e)'</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>, alpha<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>plt.legend(loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>plt.close()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="3_1_simple_linear_regression-NOTES_files/figure-html/residuals-output-1.png" id="residuals" width="789" height="390" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Minimizing the RSS using calculus gives the following formulas:</p>
<p><span class="math display">\[\hat{\beta}_1 = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n}(x_i - \bar{x})^2}, \text{and}\]</span></p>
<p><span class="math display">\[\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x},\]</span></p>
<p>where <span class="math inline">\(\bar{x} = \frac{1}{n}\sum x_i\)</span> and <span class="math inline">\(\bar{y} = \frac{1}{n}\sum y_i\)</span> are the sample means.</p>
<p>Two important points:</p>
<ol type="1">
<li><p>The <strong>optimal</strong> <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> depend entirely on the training data. Feed the same model different data and you get different estimates. This is the source of estimation uncertainty.</p></li>
<li><p>In practice, <strong>the computer computes these</strong> for you. The key is understanding what the estimates represent, not memorizing the algebra.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is the relation between the RSS and the MSE?
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the last lession we talked about the mean squared error (MSE) as a way to measure how close any estimate <span class="math inline">\(\hat{f}\)</span> is to the observed data:</p>
<p><span class="math display">\[ MSE = \frac{1}{n} \sum_{i=1}^n(y_i - \hat{f}(x_i))^2. \]</span></p>
<p>Notice that the MSE is the average of the RSS:</p>
<p><span class="math display">\[RSS = \sum_{i=1}^{n} (y_i - \hat{f}(x_i))^2.\]</span></p>
<p>Since <span class="math inline">\(n\)</span> is a positive constant, minimizing the MSE and minimizing the RSS would give the same estimates for the coefficients <span class="math inline">\(\hat{\beta}_i\)</span>.</p>
<p>However, the averaging by the dataset’s size in the MSE allows the MSE to be more meaningful as an error metric that is comparable across datasets. The RSS will always grow with as the number of observations increases.</p>
</div>
</div>
</section>
</section>
<section id="accuracy-of-the-coefficient-estimates" class="level2">
<h2 class="anchored" data-anchor-id="accuracy-of-the-coefficient-estimates">Accuracy of the coefficient estimates</h2>
<section id="standard-errors" class="level3">
<h3 class="anchored" data-anchor-id="standard-errors">Standard errors</h3>
<p>Once we have <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>, a natural question is: <em>how close are these estimates to the true <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>?</em></p>
<p>Recall that if our true function describing the relationship between predictor and response is given by <span class="math inline">\(f(X) = \beta_0 + \beta_1 X\)</span>, then our observed data is described by:</p>
<p><span class="math display">\[Y = f(X) + \epsilon = \beta_0 + \beta_1 X + \epsilon,\]</span></p>
<p>where <span class="math inline">\(\epsilon\)</span> is an error term.</p>
<p>The <strong>standard error</strong> of an estimate quantifies, on average, how far our estimates <span class="math inline">\(\hat{\beta}_i\)</span> are from the true coefficients <span class="math inline">\(\beta_i\)</span>. For the slope <span class="math inline">\(\hat{\beta}_1\)</span> the standard error is given by</p>
<p><span class="math display">\[SE(\hat{\beta}_1)^2 = \frac{\sigma^2}{\sum_{i=1}^{n}(x_i - \bar{x})^2},\]</span></p>
<p>where <span class="math inline">\(\sigma^2 = \text{Var}(\epsilon)\)</span> is the variance of the error term (assuming that the errrors <span class="math inline">\(\epsilon_i\)</span> for each observation have common variance <span class="math inline">\(\sigma^2\)</span> and are uncorrelated), and <span class="math inline">\(\bar{x} =\frac{1}{n}\sum x_i\)</span> is the average of the <span class="math inline">\(x\)</span> values.</p>
<p>The standard error of the <span class="math inline">\(y\)</span>-intercept <span class="math inline">\(\hat{\beta}_0\)</span> is:</p>
<p><span class="math display">\[SE(\hat{\beta}_0)^2 = \sigma^2 \left[\frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^{n}(x_i - \bar{x})^2}\right].\]</span></p>
<p>In practice <span class="math inline">\(\sigma^2\)</span> is unknown and must also be estimated from the data using the <strong>residual standard error</strong>, which we will talk about in a moment.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>How does the standard error for the slope estimate <span class="math inline">\(\hat{\beta_1}\)</span> change as the <span class="math inline">\(x\)</span> values are more spread out?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>As the <span class="math inline">\(x\)</span> values spread, they are further away from their mean <span class="math inline">\(\bar{x}\)</span>, this causes the sum in the denominator to increase, thus reducing the standard error <span class="math inline">\(SE(\hat{\beta}_1)^2\)</span>. This makes sense intuitively as more spread out values for <span class="math inline">\(x\)</span> should give us a better estimate for the slope of the function.</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals">Confidence intervals</h3>
<!-- Standard errors allow us to construct **confidence intervals** for the true coefficients. A **95% confidence interval** is a range of values such that, if we repeated our experiment many times, approximately 95% of the computed intervals would contain the true parameter value. -->
<p>Standard errors allow us to construct <strong>confidence intervals</strong> for the true coefficients. A <strong>95% confidence interval</strong> is a range of values such that, with 95% probability, the range will contain the true unknown value of the parameter.</p>
<p>For simple linear regression, the approximate 95% confidence interval for a coefficient <span class="math inline">\(\beta_i\)</span> is:</p>
<p><span class="math display">\[[\hat{\beta}_i - 2 \cdot SE(\hat{\beta}_i), \hat{\beta}_i + 2 \cdot SE(\hat{\beta}_i)].\]</span></p>
<p>This means there is approximately a 95% chance that the interval will contain the true vlaue for <span class="math inline">\(\beta_1\)</span>. The “approximately” is becasue the factor of 2 will vary slightly with the numnber of observations used to perform the regression. Strictly speaking, this factor will come for the 97.5% quantile of a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> degrees of freedom. In practice, we use implemented methods in our computers to calculate these confidence intervals exactly.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting the confidence interval
</div>
</div>
<div class="callout-body-container callout-body">
<p>In general terms, we interpret the confidence interval for the slope <span class="math inline">\(\hat{\beta}_1\)</span> as follows:</p>
<blockquote class="blockquote">
<p><em>a 95% confidence inerval for <span class="math inline">\(\beta_1\)</span> is <span class="math inline">\([a_1, b_1]\)</span> means that there’s a 95% chance that for an average increase of one unit of <span class="math inline">\(x\)</span>, there will be an average increase in <span class="math inline">\(y\)</span> between <span class="math inline">\(a_1\)</span> and <span class="math inline">\(b_1\)</span> units.</em></p>
</blockquote>
<p>and we interpret the confidence interval for hte intercetp <span class="math inline">\(\hat{\beta}_0\)</span> like</p>
<blockquote class="blockquote">
<p><em>a 95% confidence inerval for <span class="math inline">\(\beta_0\)</span> is <span class="math inline">\([a_0, b_0]\)</span> means that there’s a 95% chance that the linear model will intercept the <span class="math inline">\(y\)</span>-axis between <span class="math inline">\(a_0\)</span> and <span class="math inline">\(b_0\)</span>.</em></p>
</blockquote>
<p>A narrower confidence interval means our estimate is more precise. This happens when the sample size <span class="math inline">\(n\)</span> is large and when the residual variance <span class="math inline">\(\sigma^2\)</span> is small.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>The exact 95% confidence intervals for each coefficient is:</p>
<div id="d3b1af35" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ci <span class="op">=</span> res.conf_int(alpha<span class="op">=</span><span class="fl">0.05</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ci_b1_low  <span class="op">=</span> ci.loc[<span class="st">'process'</span>, <span class="dv">0</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>ci_b1_high <span class="op">=</span> ci.loc[<span class="st">'process'</span>, <span class="dv">1</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>ci_b0_low  <span class="op">=</span> ci.loc[<span class="st">'const'</span>, <span class="dv">0</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>ci_b0_high <span class="op">=</span> ci.loc[<span class="st">'const'</span>, <span class="dv">1</span>]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI for β₀ (intercept): [</span><span class="sc">{</span>ci_b0_low<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>ci_b0_high<span class="sc">:.3f}</span><span class="ss">]"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI for β₁ (process):   [</span><span class="sc">{</span>ci_b1_low<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>ci_b1_high<span class="sc">:.3f}</span><span class="ss">]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>95% CI for β₀ (intercept): [6.823, 8.567]
95% CI for β₁ (process):   [0.041, 0.051]</code></pre>
</div>
</div>
<ol type="1">
<li>What does the CI [0.041, 0.051] tell us about the relationship between process upgrade spending and CO₂ reductions?</li>
<li>What if the interval had been [-0.002, 0.051] instead?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>The entire interval [0.041, 0.051] is above 0, so with 95% confidence the slope is positive: firms that invest more in cleaner production processes achieve greater CO₂ reductions. Each additional $1K in process spending is associated with a reduction of between 0.041 and 0.051 ktCO₂e per year on average.</p></li>
<li><p>An interval of [-0.002, 0.051] includes 0. We cannot rule out that <span class="math inline">\(\beta_1 = 0\)</span>, meaning we cannot confidently conclude that process spending drives reductions. Wider intervals generally arise from smaller samples or noisier data.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis testing</h2>
<section id="the-null-and-alternative-hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="the-null-and-alternative-hypothesis">The null and alternative hypothesis</h3>
<p>A fundamental question in regression is: is there actually a relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>? We frame this as a hypothesis test:</p>
<ul>
<li><strong>Null hypothesis</strong> <span class="math inline">\(H_0\)</span>: there is no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, i.e., <span class="math inline">\(\beta_1 = 0\)</span>.</li>
<li><strong>Alternative hypothesis</strong> <span class="math inline">\(H_a\)</span>: there is some relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, i.e., <span class="math inline">\(\beta_1 \neq 0\)</span>.</li>
</ul>
<p>Note what these imply for the model:</p>
<ul>
<li>If <span class="math inline">\(\beta_1 = 0\)</span>, then <span class="math inline">\(\hat{Y} = \hat{\beta}_0\)</span>, which means the prediction is just a constant, so <span class="math inline">\(X\)</span> carries no information about <span class="math inline">\(Y\)</span>.</li>
<li>If <span class="math inline">\(\beta_1 \neq 0\)</span>, then <span class="math inline">\(\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X\)</span> — <span class="math inline">\(Y\)</span> is related to <span class="math inline">\(X\)</span>.</li>
</ul>
</section>
<section id="the-t-statistic-p-values" class="level3">
<h3 class="anchored" data-anchor-id="the-t-statistic-p-values">The <span class="math inline">\(t\)</span>-statistic &amp; <span class="math inline">\(p\)</span>-values</h3>
<p>To test <span class="math inline">\(H_0\)</span>, we need to determine whether <span class="math inline">\(\hat{\beta}_1\)</span> is sufficiently far from 0 relative to its uncertainty. We use the <strong><span class="math inline">\(t\)</span>-statistic</strong></p>
<p><span class="math display">\[t = \frac{\hat{\beta}_1}{SE(\hat{\beta}_1)}\]</span></p>
<p>which measures how many standard deviations <span class="math inline">\(\hat{\beta}_1\)</span> is away from 0. If there truly is no relationship between the variables (<span class="math inline">\(\beta_1 = 0\)</span>), then <span class="math inline">\(t\)</span> follows a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n - 2\)</span> degrees of freedom.</p>
<p>The <strong><span class="math inline">\(p\)</span>-value</strong> is the probability of observing any number equal to the <span class="math inline">\(t\)</span>-statistic <span class="math inline">\(|t|\)</span> or larger, assuming there is no relationship between the variables (i.e.&nbsp;assuming <span class="math inline">\(H_0\)</span> is true). Conventionally, <span class="math inline">\(p &lt; 0.05\)</span> is used as a threshold for rejecting <span class="math inline">\(H_0\)</span>, though the appropriate cutoff depends on context.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting the <span class="math inline">\(p\)</span>-value
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>A <strong>small <span class="math inline">\(p\)</span>-value</strong> means it is very unlikely to have observed a <span class="math inline">\(\hat{\beta}_1\)</span> this far from 0 by chance alone, if <span class="math inline">\(\beta_1\)</span> were truly 0. We <strong>reject</strong> <span class="math inline">\(H_0\)</span> and conclude there is a relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</li>
<li>A <strong>large <span class="math inline">\(p\)</span>-value</strong> means our data are consistent with <span class="math inline">\(H_0\)</span>, so we do not reject <span class="math inline">\(H_0\)</span>: it could be that there’s no relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>!</li>
</ul>
</div>
</div>
<p>A summary of this story is:</p>
<ol type="1">
<li><p>We want to know whether <span class="math inline">\(X\)</span> is related to <span class="math inline">\(Y\)</span>.</p></li>
<li><p>We compute the <span class="math inline">\(t\)</span>-statistic which is the number of standard deviations that <span class="math inline">\(\hat{\beta}_1\)</span> is away from 0.</p></li>
</ol>
<!-- 3. Assuming $\beta_1=0$ (i.e. no relationship between $X$ and $Y$) and $n>30$, then $t$'s distribution is very similar to normal distribution.  -->
<ol start="4" type="1">
<li><p>We ask the question: <em>what is the probability that <span class="math inline">\(|\hat{\beta}_1|\)</span> is more than <span class="math inline">\(t\)</span> standard deviations away from zero if the true parameter is <span class="math inline">\(\beta_1=0\)</span>?</em> This probability is the <span class="math inline">\(p\)</span>-value.</p></li>
<li><p>There are two options depending on the answer to this question:</p>
<ul>
<li>Option 1: small probability that <span class="math inline">\(\hat{\beta}_1\)</span> is that far away from 0 if the true parameter <span class="math inline">\(\beta_1=0\)</span>: so the most likely scenario is that <span class="math inline">\(\beta_1\neq0\)</span>, which means the variables are related.</li>
<li>Option 2: high probability that <span class="math inline">\(\hat{\beta}_1\)</span> is that far away from 0 is the true parameter <span class="math inline">\(\beta_1=0\)</span>: maybe <span class="math inline">\(\beta_1=0\)</span> is really zero, which means maybe there is no relationship between the variables.</li>
</ul></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>The table below shows the regression output for the SLR of <code>co2_reduction</code> on <code>process</code>:</p>
<div id="1ed369b3" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fmt_p(p):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">'&lt; 0.0001'</span> <span class="cf">if</span> p <span class="op">&lt;</span> <span class="fl">0.0001</span> <span class="cf">else</span> <span class="ss">f'</span><span class="sc">{</span>p<span class="sc">:.4f}</span><span class="ss">'</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>coef_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">''</span>:              [<span class="st">'Intercept'</span>, <span class="st">'process'</span>],</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Coefficient'</span>:   [<span class="ss">f"</span><span class="sc">{</span>res<span class="sc">.</span>params[<span class="st">'const'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>,   <span class="ss">f"</span><span class="sc">{</span>res<span class="sc">.</span>params[<span class="st">'process'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Std. error'</span>:    [<span class="ss">f"</span><span class="sc">{</span>res<span class="sc">.</span>bse[<span class="st">'const'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>,       <span class="ss">f"</span><span class="sc">{</span>res<span class="sc">.</span>bse[<span class="st">'process'</span>]<span class="sc">:.4f}</span><span class="ss">"</span>],</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'t-statistic'</span>:   [<span class="ss">f"</span><span class="sc">{</span>res<span class="sc">.</span>tvalues[<span class="st">'const'</span>]<span class="sc">:.2f}</span><span class="ss">"</span>,   <span class="ss">f"</span><span class="sc">{</span>res<span class="sc">.</span>tvalues[<span class="st">'process'</span>]<span class="sc">:.2f}</span><span class="ss">"</span>],</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'p-value'</span>:       [fmt_p(res.pvalues[<span class="st">'const'</span>]),      fmt_p(res.pvalues[<span class="st">'process'</span>])],</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(coef_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>          Coefficient Std. error t-statistic  p-value
Intercept      7.6953     0.4421       17.41 &lt; 0.0001
  process      0.0460     0.0026       17.64 &lt; 0.0001</code></pre>
</div>
</div>
<p>Looking at the regression output above:</p>
<ol type="1">
<li>What does the <span class="math inline">\(p\)</span>-value for <code>process</code> tell us about the relationship between process upgrade spending and CO₂ reductions?</li>
<li>The intercept also has a very small <span class="math inline">\(p\)</span>-value. What does this mean about the intercept estimate?</li>
<li>How would you interpret the coefficient for <code>process</code> in plain language?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>The very small <span class="math inline">\(p\)</span>-value for <code>process</code> gives strong evidence that <span class="math inline">\(\beta_1 \neq 0\)</span> — there is a statistically significant positive relationship between process upgrade investment and CO₂ emissions reductions.</p></li>
<li><p>The <span class="math inline">\(p\)</span>-value for the intercept tests <span class="math inline">\(H_0: \beta_0 = 0\)</span>, not whether the intercept is a useful predictor. A significant intercept simply means the regression line does not pass through the origin. There is likely some baseline CO₂ reduction even at zero process spending (likely from other firm-level factors not captured in the model). The intercept’s <span class="math inline">\(p\)</span>-value is rarely the question of interest.</p></li>
<li><p>A coefficient of roughly 0.046 means that, on average, each additional $1K invested in cleaner production processes is associated with approximately 0.046 ktCO₂e (46 metric tons) of additional CO₂ reduction per year.</p></li>
</ol>
</div>
</div>
</div>
</section>
</section>
<section id="assessing-model-accuracy" class="level2">
<h2 class="anchored" data-anchor-id="assessing-model-accuracy">Assessing model accuracy</h2>
<p>Beyond asking <em>whether</em> a relationship exists, we want to know <em>how well</em> the model fits the data. Two key measures are the <strong>Residual Standard Error</strong> and <strong><span class="math inline">\(R^2\)</span></strong>.</p>
<section id="residual-standard-error-rse" class="level3">
<h3 class="anchored" data-anchor-id="residual-standard-error-rse">Residual Standard Error (RSE)</h3>
<p>The <strong>RSE</strong> estimates the standard deviation of the error term <span class="math inline">\(\epsilon\)</span> and is defined as:</p>
<p><span class="math display">\[RSE = \sqrt{\frac{1}{n-2} RSS} = \sqrt{\frac{1}{n-2} \sum_{i=1}^{n}(y_i - \hat{y}_i)^2}.\]</span></p>
<p>It represents the average amount by which the response deviates from the true regression line. A smaller RSE means the model fits the data more closely.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting RSE
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>A small RSE occurs when the residuals <span class="math inline">\(y_i - \hat{y}_i\)</span> are close to 0, meaning our predictions are near the actual values.</li>
<li><em>RSE is measured in the same units as <span class="math inline">\(Y\)</span></em>, which makes it interpretable but also context-dependent.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the GreenAbate data, the RSE of the SLR on <code>process</code> is approximately 3.26 ktCO₂e. This means predictions are off by about 3,260 metric tons on average. Is this a good or bad fit? What additional information would you need to judge this?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Whether an RSE of 3.26 ktCO₂e is acceptable depends on context. A few ways to judge it:</p>
<ul>
<li><strong>Relative to the response range</strong>: CO₂ reductions in the dataset range roughly from 3 to 27 ktCO₂e, so an average error of 3.26 represents about 12–15% of the response range. That is a moderate error — not great, but not terrible.</li>
<li><strong>Relative to the mean response</strong>: the mean reduction is around 14 ktCO₂e, so the RSE is about 23% of the mean. This suggests the model has meaningful predictive error.</li>
<li><strong>Relative to the firm’s target</strong>: if a firm has committed to reducing 5 ktCO₂e per year, an average prediction error of 3.26 is large relative to their target. For a firm targeting 25 ktCO₂e, it may be acceptable.</li>
<li><strong>By adding more predictors</strong>: we are only using <code>process</code> here. Including <code>efficiency</code> and <code>offsets</code> in a multiple regression model should reduce the RSE substantially.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="r2-statistic" class="level3">
<h3 class="anchored" data-anchor-id="r2-statistic"><span class="math inline">\(R^2\)</span> statistic</h3>
<p>An easier to interpret statistic is the <strong><span class="math inline">\(R^2\)</span></strong>, which measures the <em>proportion of variance in <span class="math inline">\(Y\)</span> explained by the regression model</em>. To compute it we need these ingredients:</p>
<ul>
<li><p><span class="math inline">\(TSS = \sum_{i=1}^{n}(y_i - \bar{y})^2\)</span> is the <strong>Total Sum of Squares</strong>. This captures the inherent total variability in <span class="math inline">\(Y\)</span>, how much do the observations vary from the mean <span class="math inline">\(\bar{y}\)</span>.</p></li>
<li><p><span class="math inline">\(RSS = \sum_{i=1}^{n}(y_i - \hat{y}_i)^2\)</span> is the <strong>Residual Sum of Squares</strong>. This captures the variability in <span class="math inline">\(y\)</span> unexplained by the regression. Think about explained by regression being <span class="math inline">\(y_i = \hat{y}_i\)</span>.</p></li>
</ul>
<p>So</p>
<p><span class="math display">\[\underbrace{TSS}_{\text{total variability in }Y} - \underbrace{RSS}_{\text{unexplained by regression}} = \text{variability explained by regression}\]</span></p>
<p>We use this to define <span class="math display">\[R^2 = \frac{TSS - RSS}{TSS}.\]</span></p>
<p>So <span class="math inline">\(R^2\)</span> is the fraction of variability that the model accounts for:</p>
<p><span class="math display">\[R^2 = \frac{\text{variability explained by regression}}{\text{total variability in }Y}.\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting <span class="math inline">\(R^2\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(R^2\)</span> is always between 0 and 1.</li>
<li><span class="math inline">\(R^2\)</span> close to <strong>1</strong>: the model explains most of the variability in <span class="math inline">\(Y\)</span>: a good fit.</li>
<li><span class="math inline">\(R^2\)</span> close to <strong>0</strong>: the model explains little of the variability: <span class="math inline">\(X\)</span> alone is not capturing much of what drives <span class="math inline">\(Y\)</span>. This could mean the true relationship is non-linear, the model needs more predictors, or there is a lot of irreducible noise.</li>
<li>What counts as a “good” <span class="math inline">\(R^2\)</span> is context-dependent.</li>
<li><strong>You should always look at your data to assess linearity and an existing relationship!</strong></li>
</ul>
</div>
</div>
<!-- ### Relationship between $R^2$ and correlation

In simple linear regression (one predictor), $R^2$ is exactly the square of the **Pearson correlation** between $X$ and $Y$:

$$R^2 = r^2 = \left[\text{Cor}(X, Y)\right]^2$$

where

$$\text{Cor}(X, Y) = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{\sqrt{\sum_{i=1}^{n}(x_i - \bar{x})^2 \cdot \sum_{i=1}^{n}(y_i - \bar{y})^2}}$$

This relationship only holds for SLR — once we move to multiple predictors, $R^2$ and correlation diverge. -->
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>The table below summarizes the accuracy of the SLR of <code>co2_reduction</code> on <code>process</code>:</p>
<div id="r2-calculation" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>y_hat <span class="op">=</span> model_proc.predict(df[[<span class="st">'process'</span>]])</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>y_bar <span class="op">=</span> df[<span class="st">'co2_reduction'</span>].mean()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>TSS   <span class="op">=</span> np.<span class="bu">sum</span>((df[<span class="st">'co2_reduction'</span>] <span class="op">-</span> y_bar)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>RSS   <span class="op">=</span> np.<span class="bu">sum</span>((df[<span class="st">'co2_reduction'</span>] <span class="op">-</span> y_hat)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>R2    <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> RSS <span class="op">/</span> TSS</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>RSE   <span class="op">=</span> np.sqrt(RSS <span class="op">/</span> (n <span class="op">-</span> <span class="dv">2</span>))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>acc_df <span class="op">=</span> pd.DataFrame({</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Quantity'</span>: [<span class="st">'Residual standard error'</span>, <span class="st">'R²'</span>],</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Value'</span>:    [<span class="ss">f'</span><span class="sc">{</span>RSE<span class="sc">:.2f}</span><span class="ss">'</span>, <span class="ss">f'</span><span class="sc">{</span>R2<span class="sc">:.3f}</span><span class="ss">'</span>]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(acc_df.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Quantity Value
Residual standard error  3.14
                     R² 0.611</code></pre>
</div>
</div>
<p>For the GreenAbate SLR of <code>co2_reduction</code> on <code>process</code>, RSE = 3.14 ktCO₂e and <span class="math inline">\(R^2\)</span> = 0.611.</p>
<ol type="1">
<li>How would you interpret the <span class="math inline">\(R^2\)</span> value in plain language?</li>
<li>The RSE is 3.14 ktCO₂e. Thinking back to the RSE check-in, is this model a good fit for a firm with an annual CO₂ reduction target of 5 ktCO₂e? What about a firm targeting 25 ktCO₂e?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>An <span class="math inline">\(R^2\)</span> of 0.611 means that approximately 61.1% of the variability in CO₂ reductions across firms is explained by variation in process upgrade spending alone. The remaining ~38.9% of variability is driven by other factors not included in this model — such as efficiency upgrades, offsets, firm size, or industry type.</p></li>
<li><p>An RSE of 3.14 ktCO₂e (≈ 3138 metric tons) is large relative to, for example, a 5 ktCO₂e reduction target. A prediction error of that magnitude could meaningfully mislead decisions for a small-target firm. For a firm targeting 25 ktCO₂e, the same RSE represents roughly 13% of the target, which may or may not be acceptable depending on how precise their planning needs to be.</p></li>
</ol>
</div>
</div>
</div>
<!-- ## Recap

What we covered in this lesson:

- **Standard linear regression model:** $Y \approx \beta_0 + \beta_1 X$, estimated as $\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 x$
- Minimiinge $RSS = \sum(y_i - \hat{y}_i)^2$ gives us coeffient estimates $$\hat{\beta}_0, \hat{\beta}_1$
- Standard errors quantify uncertainty in the coefficient estimates
- Confidence intervals give us a high-probability range in which our true coefficients may be in
- We can use Hypothesis testing to figure out if there is a relationship between the variables
- $p$-value: probability of observing results there were no variable relation $(H_0)$; small $p$-value → reject $H_0$
- $R^2$: proportion of variance in $Y$ explained by $X$

Next class: multiple linear regression. -->



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-islp_2023" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, Robert Tibshirani, and Jonathan E. Taylor. 2023. <em>An Introduction to Statistical Learning: With Applications in <span>Python</span></em>. Springer Texts in Statistics. Cham: Springer.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This work is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) License</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://quarto.org/">Quarto</a> and <a href="https://github.com/MEDS-eds-220/MEDS-eds-220-course">GitHub pages</a>.</p>
</div>
  </div>
</footer>




</body></html>