---
title: Week by week
---

You will find the course announcements and daily activities here. 

## Week 1 
:::{.callout-note appearance="minimal" collapse="true" }
## What happened
1. Student introductions
2. Went over syllabus
3. Covered the [*What is ML* notes](/notes/1_0_what_is_machine_learning/1_0_what_is_machine_learning-NOTES.qmd)
4. Covered the [*Learning from data* notes](/notes/2_1_what_is_statistical_learning/2_1_what_is_statistical_learning-NOTES.qmd) and ended right before the *Parametric vs. non-parametric* section of the slides. 

### Class 1 (Tuesday)


::: {.callout-warning icon=false}
## Preparation for lab
Please complete the [setup](/notes/setup/setup.qmd) and install the class Python environment. 

⚠️ Some people have reported issues with installing the environment and some have been able to install it successfuly. We are looking into this and will reach out with updates. The workbench is already operational and available to students. 
:::

### Class 2 (Thursday)
1. Finished the [*Learning from data* notes](/notes/2_1_what_is_statistical_learning/2_1_what_is_statistical_learning-NOTES.qmd), from  *Parametric vs. non-parametric* section of the slides to the end. 
2. Covered the [*Assessing model accuracy* notes](/notes/2_2_assessing_model_accuracy/2_2_assessing_model_accuracy-NOTES.qmd)
:::

## Week 2
:::{.callout-note appearance="minimal" collapse="true" }
## What happened

### Class 1 (Tuesday)
- Covered the [*Simple linear regression* notes](/notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.qmd) up to (not including) *Assessing model accuracy*.

### Class 2 (Thursday)
- Finished the [*Simple linear regression* notes](/notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.qmd) by covering *Assessing model accuracy* section.
- Covered the [*Multiple linear regression* notes](/notes/3_2_multiple_linear_regression/3_2_multiple_linear_regression-NOTES.qmd) except for the *Variable selection* section which was assigned as reading.

:::


## Week 3
:::{.callout-note appearance="minimal" collapse="true" }
## What happened

### Class 1 (Tuesday)
- Covered the [*KNN and accuracy metrics** notes](/notes/4_1_classification/4_1_knn_accuracy_metrics-NOTES.qmd)

### Class 2 (Thursday)

:::