<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.33">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multiple linear regression – EDS 232 - Machine Learning for Environmental Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">EDS 232 - Machine Learning for Environmental Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../../notes/week-by-week/week-by-week.html" aria-current="page"> 
<span class="menu-text">notes</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-assignments" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">assignments</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-assignments">    
        <li>
    <a class="dropdown-item" href="../../assignments/assignment-1.html">
 <span class="dropdown-text">Assignment 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../assignments/assignment-2.html">
 <span class="dropdown-text">Assignment 2</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-weekly-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">weekly labs</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-weekly-labs">    
        <li>
    <a class="dropdown-item" href="../../lab/lab1.html">
 <span class="dropdown-text">Lab 01: Introduction to Machine Learning in Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../lab/lab2.html">
 <span class="dropdown-text">Lab 2: No lab this week!</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../lab/lab3.html">
 <span class="dropdown-text">Lab 3: Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../lab/lab4.html">
 <span class="dropdown-text">Lab 4: Polynomial Regression and Cross-Validation</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-study-guides" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">study guides</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-study-guides">    
        <li>
    <a class="dropdown-item" href="../../exams/exam1_study_guide.html">
 <span class="dropdown-text">Midterm Exam Study Guide</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/MEDS-eds-232/EDS-232-course-website">
 <span class="dropdown-text">Source code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/MEDS-eds-232/EDS-232-course-website/issues">
 <span class="dropdown-text">Report a bug</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html">Linear regression</a></li><li class="breadcrumb-item"><a href="../../notes/3_2_multiple_linear_regression/3_2_multiple_linear_regression-NOTES.html">Multiple linear regression</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
  <div id="quarto-announcement" data-announcement-id="c7b7782e967bb59a093245536bfed491" class="alert alert-primary hidden"><i class="bi bi-hammer quarto-announcement-icon"></i><div class="quarto-announcement-content">
<p>This wesbite is under construction.</p>
</div><i class="bi bi-x-lg quarto-announcement-action"></i></div>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/week-by-week/week-by-week.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week by week</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/setup/setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setup</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/1_0_what_is_machine_learning/1_0_what_is_machine_learning-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is machine learning?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/2_1_what_is_statistical_learning/2_1_what_is_statistical_learning-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning from data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/2_2_assessing_model_accuracy/2_2_assessing_model_accuracy-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Training and test errors, and model flexibility</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/3_2_multiple_linear_regression/3_2_multiple_linear_regression-NOTES.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Multiple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/6_linear_model_selection_and_regularization/6_linear_model_selection_and_regularization-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear model selection and regularization</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Classification</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/4_1_classification/4_1_knn_accuracy_metrics-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">KNN and accuracy metrics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/4_3_logistic_regression/4_3_logistic_regression-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logistic regression and ROC curves</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Resampling Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notes/5_1_cross_validation/5_1_cross_validation-NOTES.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cross-validation</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-guiding-example-emissions-reduction-strategies-scenario" id="toc-a-guiding-example-emissions-reduction-strategies-scenario" class="nav-link active" data-scroll-target="#a-guiding-example-emissions-reduction-strategies-scenario">A guiding example: emissions-reduction strategies scenario</a></li>
  <li><a href="#the-multiple-linear-regression-model" id="toc-the-multiple-linear-regression-model" class="nav-link" data-scroll-target="#the-multiple-linear-regression-model">The multiple linear regression model</a>
  <ul class="collapse">
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example">Example</a></li>
  <li><a href="#estimating-the-coefficients" id="toc-estimating-the-coefficients" class="nav-link" data-scroll-target="#estimating-the-coefficients">Estimating the coefficients</a></li>
  <li><a href="#p-values-for-the-coefficents" id="toc-p-values-for-the-coefficents" class="nav-link" data-scroll-target="#p-values-for-the-coefficents"><span class="math inline">\(p\)</span>-values for the coefficents</a></li>
  </ul></li>
  <li><a href="#sec-comparison" id="toc-sec-comparison" class="nav-link" data-scroll-target="#sec-comparison">Comparing MLR to individual SLRs</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing">Hypothesis testing</a>
  <ul class="collapse">
  <li><a href="#the-f-statistic" id="toc-the-f-statistic" class="nav-link" data-scroll-target="#the-f-statistic">The <span class="math inline">\(F\)</span>-statistic</a></li>
  <li><a href="#why-not-just-use-individual-p-values" id="toc-why-not-just-use-individual-p-values" class="nav-link" data-scroll-target="#why-not-just-use-individual-p-values">Why not just use individual p-values?</a></li>
  </ul></li>
  <li><a href="#model-fit-r2-in-multiple-regression" id="toc-model-fit-r2-in-multiple-regression" class="nav-link" data-scroll-target="#model-fit-r2-in-multiple-regression">Model fit: <span class="math inline">\(R^2\)</span> in multiple regression</a></li>
  <li><a href="#variable-selection" id="toc-variable-selection" class="nav-link" data-scroll-target="#variable-selection">Variable selection</a>
  <ul class="collapse">
  <li><a href="#forward-selection" id="toc-forward-selection" class="nav-link" data-scroll-target="#forward-selection">Forward selection</a></li>
  <li><a href="#backward-selection" id="toc-backward-selection" class="nav-link" data-scroll-target="#backward-selection">Backward selection</a></li>
  <li><a href="#mixed-selection" id="toc-mixed-selection" class="nav-link" data-scroll-target="#mixed-selection">Mixed selection</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../notes/3_1_simple_linear_regression/3_1_simple_linear_regression-NOTES.html">Linear regression</a></li><li class="breadcrumb-item"><a href="../../notes/3_2_multiple_linear_regression/3_2_multiple_linear_regression-NOTES.html">Multiple linear regression</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Multiple linear regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="../../notes/3_2_multiple_linear_regression/3_2_multiple_linear_regression-SLIDES.html">📊 Slides</a> / <a href="../../notes/3_2_multiple_linear_regression/3_2_multiple_linear_regression-SLIDES-BLANK.html">📊 Blank slides</a></p>
<p>In this lesson we introduce:</p>
<ul>
<li>The <strong>multiple linear regression (MLR) model</strong></li>
<li>How MLR coefficient estimates can differ from SLR estimates</li>
<li><strong>The <span class="math inline">\(F\)</span>-statistic</strong> for testing whether any predictor is related to the response</li>
<li><strong><span class="math inline">\(R^2\)</span></strong> and <strong>adjusted R^2</strong> in multiple regression</li>
<li><strong>Variable selection</strong>: forward, backward, and mixed selection strategies</li>
</ul>
<p>These notes are based on chapter 3.2 of <em>An Introduction to Statistical Learning with Applications in Python</em> <span class="citation" data-cites="islp_2023">(<a href="#ref-islp_2023" role="doc-biblioref">James et al. 2023</a>)</span>. The <strong>example data is synthetic</strong> and was generated with the aid of Claude Code for the purpose of this lesson.</p>
<!-- ## What does "linear" mean in linear regression?

A natural question when first encountering multiple linear regression is: what does "linear" actually refer to?

The short answer: **linear in the parameters**, not necessarily linear in the predictors. Consider the following model:

$$Y = \beta_0 + \beta_1 x + \beta_2 x^2 + \epsilon$$

Here the predictor $x^2$ is clearly not a linear function of $x$, but the model is still called a linear regression model because the response $Y$ depends **linearly on the coefficients** $\beta_0$, $\beta_1$, $\beta_2$. The $\beta$'s enter the model in a simple, additive way — none of them are squared, multiplied by each other, or transformed.

This means that polynomial regression, log-transformed predictors, and many other-looking models are all "linear regression" in the technical sense, as long as the coefficients appear linearly.

::: {.callout-note}
## Linear in the parameters
A model is a **linear regression model** if it can be written as:

$$Y = \beta_0 + \beta_1 f_1(x_1, \ldots, x_p) + \beta_2 f_2(x_1, \ldots, x_p) + \cdots + \beta_p f_p(x_1, \ldots, x_p) + \epsilon$$

where $f_1, \ldots, f_p$ can be any functions of the predictors. The $f_j$ might be raw predictors $x_j$, polynomial terms $x_j^2$, log transforms $\log(x_j)$, interactions $x_j \cdot x_k$, and so on. The key is that the $\beta_j$ are not transformed — they multiply $f_j$ directly.
::: -->
<section id="a-guiding-example-emissions-reduction-strategies-scenario" class="level2">
<h2 class="anchored" data-anchor-id="a-guiding-example-emissions-reduction-strategies-scenario">A guiding example: emissions-reduction strategies scenario</h2>
<p>In this lesson we use the same example dataset as in our simple linear regression lesson. In this scenario, a research consortium tracks 200 manufacturing firms across different industries and regions. For each firm they record annual spending on three emissions-reduction strategies and the resulting CO₂ savings:</p>
<ul>
<li><strong><code>process</code></strong> — investment in cleaner production processes ($K/year)</li>
<li><strong><code>efficiency</code></strong> — investment in energy efficiency upgrades ($K/year)</li>
<li><strong><code>offsets</code></strong> — carbon offset purchases ($K/year)</li>
<li><strong><code>co2_reduction</code></strong> — annual CO₂ emissions reduced (thousand metric tons, ktCO₂e)</li>
</ul>
<p>The central question is: <em>do these investments actually drive emissions reductions, and if so, by how much?</em></p>
<p>The figure below shows <code>co2_reduction</code> plotted against each predictor separately.</p>
<div id="cell-initial-data-plotting" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="3_2_multiple_linear_regression-NOTES_files/figure-html/initial-data-plotting-output-1.png" id="initial-data-plotting" width="789" height="1217" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-multiple-linear-regression-model" class="level2">
<h2 class="anchored" data-anchor-id="the-multiple-linear-regression-model">The multiple linear regression model</h2>
<p>Suppose we have a response variable <span class="math inline">\(Y\)</span> associated with <span class="math inline">\(p\)</span> predictors <span class="math inline">\(X_1, \ldots, X_p\)</span>. The <strong>multiple linear regression (MLR) model</strong> assumes the predictors are related with the response by the formula:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \epsilon,\]</span></p>
<p>where each <span class="math inline">\(\beta_j\)</span> is a number called a <strong>coefficient</strong> and <span class="math inline">\(\epsilon\)</span> is an error term.</p>
<section id="example" class="level3">
<h3 class="anchored" data-anchor-id="example">Example</h3>
<p>In our example dataset:</p>
<ul>
<li><span class="math inline">\(Y =\)</span> <code>co2_reduction</code> is the response variable</li>
<li><span class="math inline">\(p = 3\)</span> is the number of predictors</li>
<li><span class="math inline">\(X_1 =\)</span> <code>process</code> is predictor 1</li>
<li><span class="math inline">\(X_2 =\)</span> <code>efficiency</code> is predictor 2</li>
<li><span class="math inline">\(X_3 =\)</span> <code>offsets</code> is predictor 3</li>
</ul>
<p>So the MLR model takes the form:</p>
<p><span class="math display">\[\texttt{co2\_reduction} = \beta_0 + \beta_1 \cdot \texttt{process} + \beta_2 \cdot \texttt{efficiency} + \beta_3 \cdot \texttt{offsets} + \epsilon.\]</span></p>
</section>
<section id="estimating-the-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="estimating-the-coefficients">Estimating the coefficients</h3>
<p>As usual, our goal is to estimate the unknown coefficients <span class="math inline">\(\beta_i\)</span> using available data. This will give us a a function <span class="math inline">\(\hat{f}\)</span> we can use as a model for this scenario:</p>
<p><span class="math display">\[\hat{f}(X_1, \ldots, X_p) = \hat{\beta}_0 + \hat{\beta}_1X_1 + \ldots + \hat{\beta}_pX_p.\]</span></p>
<p>In this case, we have a training set <span class="math inline">\(\{(x_1, y_1), \ldots, (x_n, y_n)\}\)</span> with <span class="math inline">\(n\)</span> observations to fit the model. For each of the observations <span class="math inline">\((x_i, y_i)\)</span> we have that:</p>
<ul>
<li><span class="math inline">\(x_i = (x_{i1}, x_{i2}, \ldots, x_{ip})\)</span> is a vector of <span class="math inline">\(p\)</span> predictor values, and</li>
<li><span class="math inline">\(y_i\)</span> is the response associated to <span class="math inline">\(x_i\)</span>.</li>
</ul>
<p>Just as in a simple linear regression, we find <span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \ldots, \hat{\beta}_p\)</span> by minimizing the residual sum of squares (RSS):</p>
<p><span class="math display">\[
\begin{align}
RSS &amp;=&amp; \sum_{i=1}^{n} (y_i - \hat{f}(x_i))^2 \\
    &amp;=&amp; \sum_{i=1}^{n} (y_i - (\hat{\beta}_0 + \hat{\beta}_1x_{i1} + \ldots + \hat{\beta}_px_{ip}))^2 \\
    &amp;=&amp; \sum_{i=1}^{n} (y_i - \hat{\beta}_0 - \hat{\beta}_1x_{i1} - \ldots - \hat{\beta}_px_{ip})^2.
\end{align}
\]</span></p>
<p>Notice that the RSS is a function of the coefficients <span class="math inline">\(\hat{\beta}_i\)</span>. The values <span class="math inline">\(x_i\)</span> are fixed numbers that come from our training data. In practice, the computer finds the coefficients <span class="math inline">\(\hat{\beta}_i\)</span> that minimize the RSS for us.</p>
<!-- TO DO: would be really nice to have a small example of an RSS on two variables and graph.  -->
<p>Once we have found coefficients that minimize the <span class="math inline">\(RSS\)</span> we obtain our model</p>
<p><span class="math display">\[\hat{f}(X_1, \ldots, X_p) = \hat{\beta}_0 + \hat{\beta}_1X_1 + \ldots + \hat{\beta}_pX_p.\]</span></p>
<p>We can use <span class="math inline">\(\hat{f}\)</span> to predict what will be the value of <span class="math inline">\(Y\)</span> at a new observation <span class="math inline">\((x_1, \ldots, x_p)\)</span> by simply plugging in each <span class="math inline">\(x_i\)</span> in the corresponding variable:</p>
<p><span class="math display">\[\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 + \cdots + \hat{\beta}_p x_p.\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting the MLR coefficients
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can interpret the coefficients to gain insight about how each predictor <span class="math inline">\(X_i\)</span> is associated with the response variable <span class="math inline">\(Y\)</span>:</p>
<blockquote class="blockquote">
<p><em>the coefficient <span class="math inline">\(\hat{\beta}_j\)</span> represents the average change in <span class="math inline">\(Y\)</span> associated with a one-unit increase in <span class="math inline">\(X_j\)</span>, holding all other predictors fixed.</em></p>
</blockquote>
<p>Notice that the interpretation of each coefficient includes the crucial phrase: <em>holding all other predictors fixed</em>, which is a key difference between MLR and SLR.</p>
</div>
</div>
<p>For our example data, the estimated coefficients are:</p>
<div id="b4d3e6c4" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor MLR coeff
   process    0.0461
efficiency    0.1831
   offsets   -0.0088</code></pre>
</div>
</div>
<p>We can interpret the coefficient associated with the <code>process</code> variable as</p>
<blockquote class="blockquote">
<p><em><span class="math inline">\(\hat{\beta}_1\)</span> is the average change in CO₂ reduction associated with a $1K increase in process upgrade spending, assuming efficiency spending and offset purchases remain unchanged.</em></p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>Looking at the MLR coefficients above:</p>
<ol type="1">
<li>What is the interpretation of the <code>efficiency</code> coefficient of 0.1831?</li>
<li>What is the predicted CO₂ reduction for a firm that spends $100K on process upgrades, $20K on efficiency, and $50K on offsets?</li>
<li>The <code>offsets</code> coefficient is very small and negative. What does that mean?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p>Each additional $1K in energy efficiency upgrades is associated with 0.1831 ktCO₂e of additional CO₂ reduction, <em>holding process and offset spending constant</em>.</p></li>
<li><p>Using our model, the estimate is given by <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 \cdot 100 + \hat{\beta}_2 \cdot 20 + \hat{\beta}_3 \cdot 50.\)</span> Computing this we obtain:</p></li>
</ol>
<div id="a9f7bb75" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Predicted CO₂ reduction: 11.29 ktCO₂e</code></pre>
</div>
</div>
<ol start="3" type="1">
<li>It means if we hold process and efficiency spending constant, higher offset purchases are associated with a <em>slightly lower</em> CO₂ reduction. Remember this data is synthetically generated, the true coefficient on <code>offsets</code> in the data-generating model is <span class="math inline">\(-0.001\)</span>, which is nearly zero, so the model is recovering something close to the truth. In real data a negative coefficient like this might also reflect that firms who buy offsets have already reduced operational emissions as much as they can.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="p-values-for-the-coefficents" class="level3">
<h3 class="anchored" data-anchor-id="p-values-for-the-coefficents"><span class="math inline">\(p\)</span>-values for the coefficents</h3>
<p>In standard linear regression (SLR) we have one variable and one response being modelled by <span class="math inline">\(Y \approx \beta_0 + \beta_1X\)</span>. After we have found estimates for <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>, we can examine whether there is a relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> by computing the <span class="math inline">\(p\)</span>-value associated to <span class="math inline">\(\hat{\beta}_1\)</span>. If the <span class="math inline">\(p\)</span>-value is small enough, we conclude the coefficient <span class="math inline">\(\hat{\beta}_1\)</span> is significantly different from 0 and there is evidence of a relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>.</p>
<p>When we fit a MLR model, which has more than one variable, we can obtain the <span class="math inline">\(p\)</span>-value for each parameter <span class="math inline">\(\hat{\beta}_j\)</span>. In this case, we use the <span class="math inline">\(p\)</span>-value associated to the coefficient <span class="math inline">\(\beta_j\)</span> to understand the <em>partial effect</em> of adding the variable <span class="math inline">\(X_j\)</span> into the model, when all other variables are held fixed.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting the <span class="math inline">\(p\)</span>-value
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Small <span class="math inline">\(p\)</span>-value for <span class="math inline">\(\hat{\beta}_j\)</span> means <span class="math inline">\(X_j\)</span> is informative <em>given the other predictors are in the model</em>.</li>
<li>Large <span class="math inline">\(p\)</span>-value for <span class="math inline">\(\hat{\beta}_j\)</span> means <span class="math inline">\(X_j\)</span> adds little beyond what the others already capture.</li>
</ul>
</div>
</div>
<p>For our example data we have that:</p>
<div id="a7722d9d" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor MLR coeff MLR p-value
   process    0.0461    &lt; 0.0001
efficiency    0.1831    &lt; 0.0001
   offsets   -0.0088      0.0193</code></pre>
</div>
</div>
<p>We can interpret the <span class="math inline">\(p\)</span>-value associated with the <code>process</code> variable as</p>
<blockquote class="blockquote">
<p>there is a relationship between the <code>process</code> predictor and the response variable <code>co2_reduction</code>, when the <code>efficiency</code> and <code>offsets</code> remain fixed.</p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>offsets</code> variable has a large <span class="math inline">\(p\)</span>-value of 0.0193. What does this <span class="math inline">\(p\)</span>-value tell us in the context of this MLR model?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The large <span class="math inline">\(p\)</span>-value is detecting that <code>offset</code> spending contributes almost nothing beyond what <code>process</code> and <code>efficiency</code> already capture. In MLR, the <span class="math inline">\(p\)</span>-value for a coefficient tests whether that variable adds information <em>beyond what the other predictors already explain</em>. A large p-value for <code>offsets</code> means that, given <code>process</code> and <code>efficiency</code> are already in the model, adding offset spending does not significantly improve the fit.</p>
<p>This is different from asking whether <code>offsets</code> has any relationship with CO₂ reductions in general. If we ran an SLR of <code>co2_reduction</code> on <code>offsets</code> alone, the result might look different because the SLR coefficient would absorb any correlation between <code>offsets</code> and the other predictors.</p>
</div>
</div>
</div>
</section>
</section>
<section id="sec-comparison" class="level2">
<h2 class="anchored" data-anchor-id="sec-comparison">Comparing MLR to individual SLRs</h2>
<p>A natural question is: why bother with MLR? Why not fit one SLR for each predictor and look at the results separately?</p>
<p>The problem is that <strong>individual SLR coefficients can be misleading when predictors are correlated</strong>. When two predictors are correlated, each one’s SLR coefficient absorbs part of the other’s effect. In cases where the predictors are strongly correlated, the SLR coefficients can be substantially biased relative to the “true” marginal effects captured by the MLR coefficients.</p>
<p>For example, if firms that invest heavily in <code>process</code> upgrades tend to also invest heavily in <code>efficiency</code>, an SLR of <code>co2_reduction</code> on <code>process</code> alone will give a coefficient that also reflects some of the <code>efficiency</code> effect. The MLR coefficient for <code>process</code> strips out the <code>efficiency</code> effect and reflects only the direct relationship of <code>process</code>.</p>
<p>As seen below, in our example dataset the SLR and MLR coefficients are similar because the three predictors were drawn independently (approximately uncorrelated by construction). In real datasets, predictors are typically correlated and the divergence between SLR and MLR coefficients can be much larger, sometimes even reversing the sign of a coefficient.</p>
<div id="slr-mlr-comparison" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor SLR coeff SLR p-value MLR coeff MLR p-value
   process    0.0460    &lt; 0.0001    0.0461    &lt; 0.0001
efficiency    0.1793    &lt; 0.0001    0.1831    &lt; 0.0001
   offsets   -0.0060      0.6153   -0.0088      0.0193</code></pre>
</div>
</div>
<!-- ::: {.callout-note}
## Multicollinearity

**Multicollinearity** refers to the situation where two or more predictors are highly correlated with each other. It causes several problems:

- The individual coefficient estimates become unstable: small changes in the data can produce large changes in the estimates.
- Standard errors increase, making it harder to detect relationships.
- Coefficients become difficult to interpret because it is hard to isolate the effect of one predictor while holding others constant.

Multicollinearity does **not** affect the model's predictions — only the interpretability and stability of individual coefficients.
::: -->
</section>
<section id="hypothesis-testing" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-testing">Hypothesis testing</h2>
<p>Through hypothsis testing, we investigate whether there are relations between the predictors and the responses.</p>
<p>Remember that in SLR, <span class="math display">\[Y \approx \beta_0 + \beta_1 X,\]</span></p>
<p>so no relationship between <span class="math inline">\(Y\)</span> and the predictor <span class="math inline">\(X\)</span> occurs when <span class="math inline">\(\beta_1=0\)</span>. Our hypotheses for the SLR hypothesis test then were:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1=0 \Rightarrow\)</span> no relationship between response and predictor, and</li>
<li><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\beta_1\neq0 \Rightarrow\)</span> some relationship between response and predictor.</li>
</ul>
<p>To investigate whether <span class="math inline">\(H_0\)</span> is true, we test how far <span class="math inline">\(\hat{\beta}_1\)</span> is from 0 relative to its uncertainty: this is what the <span class="math inline">\(t\)</span>-statistic measures. We then ask what is the probability to observe at <span class="math inline">\(t\)</span> value as extreme as this if <span class="math inline">\(\beta_1=0\)</span>: this probability is the <span class="math inline">\(p\)</span>-value. If the <span class="math inline">\(p\)</span>-value is small, then there is evidence of a relationship.</p>
<p>For multiple regression we have that</p>
<p><span class="math display">\[Y \approx \beta_0 + \beta_1X_1 + \ldots + \beta_p X_p,\]</span></p>
<p>so no relationship between <span class="math inline">\(Y\)</span> and the predictors <span class="math inline">\(X_1, \ldots, X_p\)</span> happens when <span class="math inline">\(\beta_1 = \ldots = \beta_p = 0\)</span>. So our hypotheses this time are:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 =... =\beta_p=0 \Rightarrow\)</span> no relationship between <span class="math inline">\(Y\)</span> and <em>any</em> predictor <span class="math inline">\(X_1, \ldots, X_p\)</span>, and</li>
<li><span class="math inline">\(H_a\)</span>: at least one <span class="math inline">\(\beta_j \neq 0 \Rightarrow\)</span> some relationship between response and <em>some</em> predictor.</li>
</ul>
<p>Effectively, we are investigating the question <em>Is any predictor related to the response?</em></p>
<section id="the-f-statistic" class="level3">
<h3 class="anchored" data-anchor-id="the-f-statistic">The <span class="math inline">\(F\)</span>-statistic</h3>
<p>Instead of the <span class="math inline">\(t\)</span>-statistic, to test these hypotheses we use the <strong><span class="math inline">\(F\)</span>-statistic</strong>:</p>
<p><span class="math display">\[F = \frac{(TSS - RSS)/p}{RSS/(n - p - 1)}\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(TSS = \sum(y_i - \bar{y})^2\)</span> is the total variability in <span class="math inline">\(Y\)</span>,</li>
<li><span class="math inline">\(RSS = \sum(y_i - \hat{y}_i)^2\)</span> is the variability unexplained by the model,</li>
<li><span class="math inline">\(p\)</span> is the number of predictors,</li>
<li><span class="math inline">\(n\)</span> is the number of observations in our training data, and</li>
<li><span class="math inline">\(n - p - 1\)</span> are the residual degrees of freedom.</li>
</ul>
<p>The numerator measures how much variance the predictors collectively explain; the denominator measures how much variance remains unexplained per degree of freedom.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpreting the <span class="math inline">\(F\)</span>-statistic
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>If <span class="math inline">\(H_0\)</span> is true (no predictor is related to <span class="math inline">\(Y\)</span>), we expect <span class="math inline">\(F \approx 1\)</span>. This means the explained variance is about the same as the unexplained variance per degree of freedom.</li>
<li>If <span class="math inline">\(H_a\)</span> is true (at least one predictor is related), the numerator will be larger than the denominator, giving <span class="math inline">\(F &gt; 1\)</span>. The larger the <span class="math inline">\(F\)</span>, the stronger the evidence against <span class="math inline">\(H_0\)</span>.</li>
</ul>
</div>
</div>
<p>Finally, after we have the <span class="math inline">\(F\)</span>-statistic, we ask: what is the probability of observing an <span class="math inline">\(F\)</span> this large (or larger) assuming <span class="math inline">\(H_0\)</span> is true? This probability is the <strong><span class="math inline">\(p\)</span>-value</strong> for the <span class="math inline">\(F\)</span>-statistic. As before, a small <span class="math inline">\(p\)</span>-value implies we can reject <span class="math inline">\(H_0\)</span> and at least one predictor is associated with the response.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>For our example MLR, the <span class="math inline">\(F\)</span>-statistic is 612.1 with an associated <span class="math inline">\(p\)</span>-value of &lt; 0.0001. What can we say about the relation of <code>co2_reduction</code> with the predictors?</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>An <span class="math inline">\(F\)</span>-statistic of 612.1 (with <span class="math inline">\(p \ll 0.05\)</span>) gives very strong evidence that at least one of the three predictors is associated with CO₂ reductions. We reject <span class="math inline">\(H_0\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="why-not-just-use-individual-p-values" class="level3">
<h3 class="anchored" data-anchor-id="why-not-just-use-individual-p-values">Why not just use individual p-values?</h3>
<p>You might wonder: if we already have a <span class="math inline">\(p\)</span>-value for each coefficient, why do we need the <span class="math inline">\(F\)</span>-statistic and its <span class="math inline">\(p\)</span>-value?</p>
<p>When the number of predictors <span class="math inline">\(p\)</span> is large, some individual <span class="math inline">\(p\)</span>-values will be small <em>just by chance</em>, even when none of the predictors are truly related to <span class="math inline">\(Y\)</span>. For example, suppose that <span class="math inline">\(p = 100\)</span> and all null hypotheses <span class="math inline">\(H_0: \beta_j = 0\)</span> are true, so no variable is truly associated with the response. We would still expect about 5 of the 100 <span class="math inline">\(p\)</span>-values to fall below 0.05 by random chance alone.</p>
<p>The <span class="math inline">\(F\)</span>-statistic jointly tests all coefficients at once and naturally accounts for the number of predictors, making it the correct first tool for asking “is <em>any</em> predictor related to <span class="math inline">\(Y\)</span>?”</p>
<p>Overall, when <span class="math inline">\(p\)</span> is small relative to <span class="math inline">\(n\)</span>, the <span class="math inline">\(F\)</span>-test and the individual <span class="math inline">\(t\)</span>-tests tend to agree. The <span class="math inline">\(F\)</span>-test becomes especially important when <span class="math inline">\(p\)</span> is large. Relying on individual <span class="math inline">\(p\)</span>-values alone in that setting can lead to incorrect conclusions. <!-- 
:::{.callout-tip}
## Check-in

For our example MLR, the $F$-statistic is 612\.1 with an associated $p$-value of < 0\.0001. In addition, when we run individual regressions of 

::: {#7737892b .cell execution_count=8}

::: {.cell-output .cell-output-stdout}
```
           Coefficient t-statistic  p-value
 Intercept      3.4543       10.11 < 0.0001
   process      0.0461       35.37 < 0.0001
efficiency      0.1831       24.37 < 0.0001
   offsets     -0.0088       -2.36   0.0193
```
:::
:::


2. Looking at the individual $p$-values in the coefficient table, which predictor(s) appear significantly related to CO₂ reductions?
3. The `offsets` $p$-value is large. Does this mean offset purchases have no effect on CO₂ reductions in reality?
:::

:::{.callout-tip collapse="true"}
## Discussion

2. Both `process` and `efficiency` have very small $p$-values ($p < 0.0001$), providing strong individual evidence of an association after accounting for the other predictors. `offsets` has a large $p$-value, suggesting it adds little beyond what `process` and `efficiency` already explain.

3. Not necessarily. The `offsets` $p$-value says that, *in the context of a model that already includes `process` and `efficiency`*, additional offset spending is not significantly associated with CO₂ reductions. The true coefficient in our data-generating model is $-0.001$, which is effectively zero — so the data is correctly telling us that `offsets` contributes almost nothing. In general, a large $p$-value for one predictor in an MLR does not mean the variable has no effect overall; it means it adds little **beyond what the other predictors already capture**.
::: --></p>
</section>
</section>
<section id="model-fit-r2-in-multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="model-fit-r2-in-multiple-regression">Model fit: <span class="math inline">\(R^2\)</span> in multiple regression</h2>
<p>The <span class="math inline">\(R^2\)</span> statistic is defined the same way as in SLR:</p>
<p><span class="math display">\[R^2 = 1 - \frac{RSS}{TSS}\]</span></p>
<p>It still measures the proportion of variance in <span class="math inline">\(Y\)</span> explained by the model. However, in MLR there is an important caveat: adding a predictor to the model will always increase <span class="math inline">\(R^2\)</span> (or leave it unchanged), even if that predictor has no real relationship with <span class="math inline">\(Y\)</span>. This happens because any additional variable can absorb a small amount of random noise in the training data, reducing the RSS slightly.</p>
<p>In addition, <span class="math inline">\(R^2\)</span> never decreases when predictors are added, using it alone to compare models with different numbers of predictors can be misleading. The <strong>adjusted <span class="math inline">\(R^2\)</span></strong> corrects for this by penalizing the model for each additional predictor:</p>
<p><span class="math display">\[\bar{R}^2 = 1 - \frac{RSS/(n-p-1)}{TSS/(n-1)}\]</span></p>
<p>Unlike <span class="math inline">\(R^2\)</span>, the adjusted <span class="math inline">\(R^2\)</span> can decrease when adding a predictor that does not improve the fit enough to justify the added complexity. It is therefore a better criterion for comparing models of different sizes.</p>
</section>
<section id="variable-selection" class="level2">
<h2 class="anchored" data-anchor-id="variable-selection">Variable selection</h2>
<p>Once we decide to use multiple linear regression we follow the steps:</p>
<ol type="1">
<li>Fit the model</li>
<li>Compute <span class="math inline">\(F\)</span>-statistics and its <span class="math inline">\(p\)</span>-value</li>
<li>Check individual <span class="math inline">\(p\)</span>-values for predictors.</li>
</ol>
<p>If there’s evidence that <em>some</em> predictors are associated with the response, an important question is: <em>which predictors should we include in the model?</em> This is called <strong>variable selection</strong>. This is an important question to resolve since including unnecessary predictors does not help predictions and increases variance; leaving out important ones biases our estimates.</p>
<p>With <span class="math inline">\(p\)</span> predictors there are <span class="math inline">\(2^p\)</span> possible subsets of variables to consider. For even moderate <span class="math inline">\(p\)</span> (say, 30 or 40) this is completely infeasible to try exhaustively. Three common automated approaches are:</p>
<section id="forward-selection" class="level3">
<h3 class="anchored" data-anchor-id="forward-selection">Forward selection</h3>
<p>Start with the simplest model and build up:</p>
<ol type="1">
<li>Start with the null model: only an intercept, no predictors.</li>
<li>Fit <span class="math inline">\(p\)</span> simple regressions (one per predictor) and add the predictor that results in the lowest RSS.</li>
<li>Fit all two-variable models that include the predictor chosen in step 2, and add the next predictor that gives the lowest RSS.</li>
<li>Continue adding predictors until a stopping criterion is met (e.g., no remaining predictor produces a statistically significant improvement).</li>
</ol>
<p>Forward selection is always applicable, but it might include variables early that later become redundant.</p>
</section>
<section id="backward-selection" class="level3">
<h3 class="anchored" data-anchor-id="backward-selection">Backward selection</h3>
<p>Start with the most complex model and simplify:</p>
<ol type="1">
<li>Start with the full model, the MLR with all <span class="math inline">\(p\)</span> predictors included.</li>
<li>Remove the predictor with the largest <span class="math inline">\(p\)</span>-value (least statistically significant).</li>
<li>Refit the model with the remaining <span class="math inline">\(p-1\)</span> predictors and repeat.</li>
<li>Stop when all remaining predictors are significant at the chosen threshold.</li>
</ol>
<p>Backward selection cannot be used when <span class="math inline">\(p &gt; n\)</span> (more predictors than observations), because the full model cannot be fit.</p>
</section>
<section id="mixed-selection" class="level3">
<h3 class="anchored" data-anchor-id="mixed-selection">Mixed selection</h3>
<p>Mixed selection combines the forward and backward approaches to avoid their respective limitations:</p>
<ol type="1">
<li>Start with the null model.</li>
<li>Forward step: add the variable that most improves the model (largest reduction in RSS).</li>
<li>Backward step: after each addition, check if any currently included variable now has a <span class="math inline">\(p\)</span>-value above the removal threshold. Adding a new variable can sometimes make a previously added one redundant. If so, remove it.</li>
<li>Continue alternating forward and backward steps until no variables are added or removed.</li>
</ol>
<p>This addresses the main limitation of forward selection: a variable added early can become unnecessary once other variables are included. Mixed selection allows such variables to be dropped rather than staying in the model indefinitely.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Check-in
</div>
</div>
<div class="callout-body-container callout-body">
<p>For our example dataset, there are <span class="math inline">\(2^3 = 8\)</span> possible subsets of the three predictors. The table below shows the RSS for every possible model:</p>
<div id="all-models-rss" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>           Predictors in model    RSS
              (intercept only) 5016.8
                       process 1950.3
                    efficiency 3601.4
                       offsets 5010.4
          process + efficiency  497.5
             process + offsets 1949.8
          efficiency + offsets 3571.4
process + efficiency + offsets  483.8</code></pre>
</div>
</div>
<p>Using the table above, manually trace through the three steps of forward selection:</p>
<ol type="1">
<li><strong>Step 1</strong> — Start with the null model. Which single predictor gives the largest reduction in RSS? What would be the RSS after adding it?</li>
<li><strong>Step 2</strong> — With that predictor already in the model, which one would be added in second place?</li>
<li><strong>Step 3</strong> — Adding the final predictor, does it meaningfully reduce the RSS compared to the two-predictor model? What criteria could be used to decide whether to add or not the final predictor?</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Discussion
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Step 1</strong>: Comparing the three single-predictor models, <code>process</code> gives the lowest RSS. Forward selection adds <code>process</code> first. This is consistent with the scatter plots seen earlier, where <code>process</code> showed the strongest linear association with CO₂ reductions.</p></li>
<li><p><strong>Step 2</strong>: With <code>process</code> already included, we compare <code>process + efficiency</code> and <code>process + offsets</code>. The <code>process + efficiency</code> model has the lower RSS, so <code>efficiency</code> is added second. The reduction from step 1 to step 2 is substantial, reflecting that <code>efficiency</code> spending is genuinely associated with CO₂ reductions in the data-generating model.</p></li>
<li><p><strong>Step 3</strong>: Adding <code>offsets</code> to the two-predictor model produces only a very small further reduction in RSS. This matches its near-zero true coefficient (<span class="math inline">\(-0.001\)</span>) and large <span class="math inline">\(p\)</span>-value in the MLR output. Whether we include <code>offsets</code> at this step depends on the stopping criterion: if we require a minimum RSS improvement, it would likely not be added.</p></li>
</ol>
</div>
</div>
</div>
<p>Forward and backward selection can be run using metrics other than RSS. In fact, using raw RSS as the sole criterion would always favor adding more predictors (RSS can only decrease or stay the same when a predictor is added). An alternative that penalizes model complexity is using the adjusted <span class="math inline">\(R^2\)</span>.</p>
<!-- TODO: there's more topics 3.3+ that I would like to cover in the future -->



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-islp_2023" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, Robert Tibshirani, and Jonathan E. Taylor. 2023. <em>An Introduction to Statistical Learning: With Applications in <span>Python</span></em>. Springer Texts in Statistics. Cham: Springer.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This work is licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC Attribution-NonCommercial 4.0 International (CC BY-NC 4.0) License</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>This website is built with <a href="https://quarto.org/">Quarto</a> and <a href="https://github.com/MEDS-eds-220/MEDS-eds-220-course">GitHub pages</a>.</p>
</div>
  </div>
</footer>




</body></html>