<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ea385d0e468b0dd5ea5bf0780b1290d9.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.33">

  <title>EDS 232 - Machine Learning for Environmental Science – multiple_linear_regression-slides-blank</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-aa079427e74470e351a8ef456b814408.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section id="title-slide" class="slide level2 center" data-menu-title="Title Slide" data-background="#053660">
<h2></h2>
<p><span class="custom-title">EDS 232</span></p>
<hr class="hr-teal">
<p><span class="custom-subtitle">Lesson 4</span></p>
<p><span class="custom-subtitle"><em>Multiple linear regression</em></span></p>
</section>
<section id="in-this-lesson" class="slide level2" data-menu-title="In this lesson">
<h2></h2>
<p><span class="slide-title">In this lesson</span></p>
<hr>
<p><br></p>
<ul>
<li>The multiple linear regression (MLR) model</li>
<li>Comparing MLR to individual SLRs</li>
<li>Hypothesis testing and the <span class="math inline">\(F\)</span>-statistic</li>
<li>Model fit: <span class="math inline">\(R^2\)</span> in MLR and adjusted <span class="math inline">\(R^2\)</span></li>
<li>Variable selection: forward, backward, and mixed</li>
</ul>
</section>
<section id="section-example" class="slide level2" data-menu-title="# A guiding example #" data-background="#047C90">
<h2></h2>
<div class="page-center vertical-center">
<p class="custom-subtitle bottombr">
A guiding example
</p>
</div>
</section>
<section id="greenabate" class="slide level2" data-menu-title="The GreenAbate dataset">
<h2></h2>
<p><span class="slide-title">Our example dataset</span></p>
<hr>
<p>A research consortium tracks <strong>200 manufacturing firms</strong>. For each firm, they record annual spending on three emissions-reduction strategies and the resulting CO₂ savings:</p>
<p><br></p>
<div class="body-text-m">
<ul>
<li><strong><code>process</code></strong> — investment in cleaner production processes ($K/year)</li>
<li><strong><code>efficiency</code></strong> — investment in energy efficiency upgrades ($K/year)</li>
<li><strong><code>offsets</code></strong> — carbon offset purchases ($K/year)</li>
<li><strong><code>co2_reduction</code></strong> — annual CO₂ emissions reduced (ktCO₂e/year)</li>
</ul>
</div>
<p>The researchers want to understand:</p>
<div class="center-text body-text-m teal-text">
<p><em>Do these investments actually drive emissions reductions, and if so, by how much?</em></p>
</div>
</section>
<section id="greenabate-plots" class="slide level2" data-menu-title="GreenAbate: data overview">
<h2></h2>
<p><span class="slide-title">CO₂ reduction vs.&nbsp;each predictor</span></p>
<hr>
<div id="44f73faf" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3_2_multiple_linear_regression-SLIDES-BLANK_files/figure-revealjs/cell-3-output-1.png" class="quarto-figure quarto-figure-center" width="1187" height="390"></p>
</figure>
</div>
</div>
</div>
<div class="center-text body-text-s">
<p><em>Synthetic data generated for educational purposes only</em></p>
</div>
</section>
<section id="mlr-motivation" class="slide level2" data-menu-title="From SLR to MLR">
<h2></h2>
<p><span class="slide-title">From SLR to MLR</span></p>
<hr>
<p>In SLR we modelled the relationship between <strong>one</strong> predictor and a response:</p>
<p><span class="math display">\[\texttt{co2_reduction} \approx \hat{\beta}_0 + \hat{\beta}_1 \cdot \texttt{process}.\]</span></p>
<p>Our example dataset has three potential predictors.</p>
<p>Running separate SLRs has the problem that each SLR ignores the other predictors.</p>
<p><br></p>
<div class="center-text teal-text body-text-m">
<p><strong>Multiple linear regression</strong> handles all predictors simultaneously.</p>
</div>
</section>
<section id="section-mlr" class="slide level2" data-menu-title="# The MLR model #" data-background="#047C90">
<h2></h2>
<div class="page-center vertical-center">
<p class="custom-subtitle bottombr">
The multiple linear regression model
</p>
</div>
</section>
<section id="mlr-model-1" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">The MLR model</span></p>
<hr>
<div style="position: absolute; bottom: 550px; right: 1000px; font-size: 1em;">
<p>✏️</p>
</div>
</section>
<section id="mlr-model-2" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">The MLR model</span></p>
<hr>
<p>With <span class="math inline">\(p\)</span> predictors <span class="math inline">\(X_1, \ldots, X_p\)</span> and response variable <span class="math inline">\(Y\)</span>, the <strong>multiple linear regression (MLR) model</strong> assumes the predictors and response are related by:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \epsilon,\]</span></p>
<p>each <span class="math inline">\(\beta_i\)</span> is a <strong>coefficient</strong> and <span class="math inline">\(\epsilon\)</span> is an error term.</p>
<p>In our example data</p>
<div class="columns">
<div class="column" style="width:50%;">
<ul>
<li><span class="math inline">\(Y =\)</span> <code>co2_reduction</code> is the response variable</li>
<li><span class="math inline">\(p = 3\)</span> is the number of predictors</li>
</ul>
</div><div class="column" style="width:50%;">
<ul>
<li><span class="math inline">\(X_1 =\)</span> <code>process</code> is predictor 1</li>
<li><span class="math inline">\(X_2 =\)</span> <code>efficiency</code> is predictor 2</li>
<li><span class="math inline">\(X_3 =\)</span> <code>offset</code> is predictor 3</li>
</ul>
</div></div>
<p>So the MLR model takes the form:</p>
<p><span class="math display">\[\texttt{co2_reduction} = \beta_0 + \beta_1 \cdot \texttt{process} + \beta_2 \cdot \texttt{efficiency} + \beta_3 \cdot \texttt{offsets} + \epsilon.\]</span></p>
</section>
<section id="estimating-coefficients-1" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">Estimating the MLR coefficients</span></p>
<hr>
<div style="position: absolute; bottom: 550px; right: 1000px; font-size: 1em;">
<p>✏️</p>
</div>
</section>
<section id="estimating-coefficients" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">Estimating the MLR coefficients</span></p>
<hr>
<p>In the MLR model we assume: <span class="math inline">\(Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \cdots + \beta_p X_p + \epsilon.\)</span></p>
<p>Our goal is to estimate the coefficients and obtain a model</p>
<p><span class="math display">\[\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X_1 + \hat{\beta}_2 X_2 + \cdots + \hat{\beta}_p X_p.\]</span></p>
<p>Our training set is <span class="math inline">\(\{(x_1, y_1), \ldots, (x_n, y_n)\}\)</span> with <span class="math inline">\(n\)</span> observations.</p>
<p>For each of the observations <span class="math inline">\((x_i, y_i)\)</span> we have that:</p>
<ul>
<li><span class="math inline">\(x_i = (x_{i1}, x_{i2}, \ldots, x_{ip})\)</span> is a vector of <span class="math inline">\(p\)</span> predictor values, and</li>
<li><span class="math inline">\(y_i\)</span> is the response associated to <span class="math inline">\(x_i\)</span>.</li>
</ul>
<p>We estimate the coefficients/fit the model by finding the <span class="math inline">\(\hat{\beta}_i\)</span> that minimize the residual sum of squares (same procedure as SLR!):</p>
<p><span class="math display">\[
RSS = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2 = \sum_{i=1}^{n} (y_i - \hat{\beta}_0 - \hat{\beta}_1x_{i1} - \ldots - \hat{\beta}_px_{ip})^2 .
\]</span></p>
</section>
<section id="regression-plane-1" class="slide level2" data-menu-title="The regression plane">
<h2></h2>
<p><span class="slide-title">From a line to a plane</span></p>
<hr>
<div id="d01b634b" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3_2_multiple_linear_regression-SLIDES-BLANK_files/figure-revealjs/cell-4-output-1.png" class="quarto-figure quarto-figure-center" width="558" height="549"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regression-plane-2" class="slide level2" data-menu-title="The regression plane">
<h2></h2>
<p><span class="slide-title">From a line to a plane</span></p>
<hr>
<div id="fb013c59" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="3_2_multiple_linear_regression-SLIDES-BLANK_files/figure-revealjs/cell-5-output-1.png" class="quarto-figure quarto-figure-center" width="558" height="549"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="mlr-coeffs-1" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">Interpreting the MLR coefficients</span></p>
<hr>
<div class="page-center vertical-center">
<p>Once we find the coefficients that minimize the RSS we obtain a model:</p>
<p><span class="math display">\[\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X_1 + \hat{\beta}_2 X_2 + \cdots + \hat{\beta}_p X_p\]</span></p>
<p>We interpret each coefficient as</p>
<p><br> <br> <br> <br> <br> <br></p>
</div>
<div style="position: absolute; bottom: 300px; right: 1000px; font-size: 1em;">
✏️<br>

</div>
</section>
<section id="mlr-coeffs" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">Interpreting the MLR coefficients</span></p>
<hr>
<div class="page-center vertical-center">
<p>Once we find the coefficients that minimize the RSS we obtain a model:</p>
<p><span class="math display">\[\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X_1 + \hat{\beta}_2 X_2 + \cdots + \hat{\beta}_p X_p\]</span></p>
<p>We interpret each coefficient as</p>
<blockquote>
<p><em><span class="math inline">\(\hat{\beta}_j\)</span> is the average change in <span class="math inline">\(Y\)</span> associated with a one-unit increase in <span class="math inline">\(X_j\)</span>, <strong>holding all other predictors constant</strong>.</em></p>
</blockquote>
</div>
</section>
<section id="check-in-coeffs" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<p>For our example data, the estimated coefficients are:</p>
<div id="261d892b" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor MLR coeff
   process    0.0461
efficiency    0.1831
   offsets   -0.0088</code></pre>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="teal-text">
<ol type="1">
<li>What is the interpretation of the <code>efficiency</code> coefficient of 0.1831?</li>
<li>How do we calculate the predicted CO₂ reduction for a firm that spends $100K on process upgrades, $20K on efficiency, and $50K on offsets?</li>
<li>The <code>offsets</code> coefficient is very small and negative. What does that mean?</li>
</ol>
</div>
</div><div class="column" style="width:50%;">

</div></div>
</section>
<section id="check-in-coeffs-answers" class="slide level2" data-menu-title="The MLR model">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<p>For our example data, the estimated coefficients are:</p>
<div id="b8cadba7" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor MLR coeff
   process    0.0461
efficiency    0.1831
   offsets   -0.0088</code></pre>
</div>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="teal-text">
<ol type="1">
<li>What is the interpretation of the <code>efficiency</code> coefficient of 0.1831?</li>
<li>How do we calculate the predicted CO₂ reduction for a firm that spends $100K on process upgrades, $20K on efficiency, and $50K on offsets?</li>
<li>The <code>offsets</code> coefficient is very small and negative. What does that mean?</li>
</ol>
</div>
</div><div class="column" style="width:50%;">
<div class="body-text-s">
<ol type="1">
<li><p>Each additional $1K in energy efficiency upgrades is associated with 0.1831 ktCO₂e of additional CO₂ reduction, <em>holding process and offset spending constant</em>.</p></li>
<li><p>Using our model, the estimate is given by <span class="math inline">\(\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 \cdot 100 + \hat{\beta}_2 \cdot 20 + \hat{\beta}_3 \cdot 50 \approx 11.29\)</span> ktCO₂e.</p></li>
<li><p>It means if we hold process and efficiency spending constant, higher offset purchases are associated with a <em>slightly lower</em> CO₂ reduction.</p></li>
</ol>
</div>
</div></div>
</section>
<section id="pvalues-mlr" class="slide level2" data-menu-title="Individual p-values in MLR">
<h2></h2>
<p><span class="slide-title"><span class="math inline">\(p\)</span>-values for the coefficients</span></p>
<hr>
<p>In SLR, the <span class="math inline">\(p\)</span>-value for <span class="math inline">\(\hat{\beta}_1\)</span> tests <span class="math inline">\(H_0: \beta_1 = 0\)</span>, which means <em>is <span class="math inline">\(X\)</span> related to <span class="math inline">\(Y\)</span>?</em></p>
<div class="fragment">
<p>In MLR, the <span class="math inline">\(p\)</span>-value for each <span class="math inline">\(\hat{\beta}_j\)</span> tests <span class="math inline">\(H_0: \beta_i =0\)</span>, which means <em>is <span class="math inline">\(X_i\)</span> related to <span class="math inline">\(Y\)</span> if all other predictor are in the model?</em></p>
<p>So <span class="math inline">\(H_0\)</span> for MLR is about the <strong>partial effect</strong> of <span class="math inline">\(X_j\)</span>. We are trying to answer:</p>
<div class="center-text">
<p><em>Does <span class="math inline">\(X_j\)</span> add information beyond what the other predictors already explain?</em></p>
</div>
<p><br></p>
</div>
<div class="fragment">
<p>We can interpret the individual <span class="math inline">\(p\)</span>-values from the MLR as</p>
<ul>
<li>Small <span class="math inline">\(p\)</span>-value for <span class="math inline">\(\hat{\beta}_j\)</span> → <span class="math inline">\(X_j\)</span> is informative <strong>given the other predictors are in the model</strong></li>
<li>Large <span class="math inline">\(p\)</span>-value for <span class="math inline">\(\hat{\beta}_j\)</span> → <span class="math inline">\(X_j\)</span> adds little beyond what the others already capture</li>
</ul>
</div>
</section>
<section id="check-in-p-values" class="slide level2" data-menu-title="Check-in">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<p>For our example data we have that:</p>
<div id="9f32f781" class="cell" data-execution_count="7">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor MLR coeff MLR p-value
   process    0.0461    &lt; 0.0001
efficiency    0.1831    &lt; 0.0001
   offsets   -0.0088      0.0193</code></pre>
</div>
</div>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="teal-text">
<ol type="1">
<li><p>How can we interpret the <span class="math inline">\(p\)</span>-value associated with the <code>process</code> variable?</p></li>
<li><p>The <code>offsets</code> variable has a large <span class="math inline">\(p\)</span>-value of 0.0193. What does it tell us in the context of this MLR model?</p></li>
</ol>
</div>
</div><div class="column" style="width:50%;">

</div></div>
</section>
<section id="check-in-p-values-answers" class="slide level2" data-menu-title="Check-in">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<p>For our example data we have that:</p>
<div id="9bf7f176" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor MLR coeff MLR p-value
   process    0.0461    &lt; 0.0001
efficiency    0.1831    &lt; 0.0001
   offsets   -0.0088      0.0193</code></pre>
</div>
</div>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="teal-text">
<ol type="1">
<li><p>How can we interpret the <span class="math inline">\(p\)</span>-value associated with the <code>process</code> variable?</p></li>
<li><p>The <code>offsets</code> variable has a large <span class="math inline">\(p\)</span>-value of 0.0193. What does it tell us in the context of this MLR model?</p></li>
</ol>
</div>
</div><div class="column" style="width:50%;">
<ol type="1">
<li><p>There is a relationship between the <code>process</code> predictor and the response variable <code>co2_reduction</code>, when the <code>efficiency</code> and <code>offsets</code> remain fixed.</p></li>
<li><p>It is detecting that <code>offset</code> spending contributes almost nothing beyond what <code>process</code> and <code>efficiency</code> already capture.</p></li>
</ol>
</div></div>
</section>
<section id="section-comparison" class="slide level2" data-menu-title="# MLR vs. individual SLRs #" data-background="#047C90">
<h2></h2>
<div class="page-center vertical-center">
<p class="custom-subtitle bottombr">
Comparing MLR to individual SLRs
</p>
</div>
</section>
<section id="slr-vs-mlr-1" class="slide level2" data-menu-title="SLR vs. MLR coefficients">
<h2></h2>
<p><span class="slide-title">SLR vs.&nbsp;MLR: why not just run <span class="math inline">\(p\)</span> separate regressions?</span></p>
<hr>
<ul>
<li><strong>individual SLR coefficients can be misleading when predictors are correlated</strong></li>
<li>When two predictors are correlated, each one’s SLR coefficient absorbs part of the other’s effect.</li>
</ul>
<div class="fragment">
<p><em>Example</em></p>
<p>Suppose firms that invest heavily in <code>process</code> upgrades tend to also invest heavily in <code>efficiency</code>.</p>
<ul>
<li>An SLR of <code>co2_reduction</code> on <code>process</code> alone will give a coefficient that also reflects some of the <code>efficiency</code> effect.</li>
<li>The MLR coefficient for <code>process</code> strips out the <code>efficiency</code> effect and reflects only the direct relationship of <code>process</code>.</li>
</ul>
</div>
</section>
<section id="slr-vs-mlr-2" class="slide level2" data-menu-title="SLR vs. MLR coefficients">
<h2></h2>
<p><span class="slide-title">SLR vs.&nbsp;MLR: why not just run <span class="math inline">\(p\)</span> separate regressions?</span></p>
<hr>
<ul>
<li><strong>individual SLR coefficients can be misleading when predictors are correlated</strong></li>
<li>When two predictors are correlated, each one’s SLR coefficient absorbs part of the other’s effect.</li>
</ul>
<p><em>Example</em></p>
<div class="body-text-s">
<p>In our example dataset, SLR ≈ MLR coefficients because the predictors were drawn independently (uncorrelated by construction).</p>
</div>
<div id="f243d808" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor SLR coeff SLR p-value MLR coeff MLR p-value
   process    0.0460    &lt; 0.0001    0.0461    &lt; 0.0001
efficiency    0.1793    &lt; 0.0001    0.1831    &lt; 0.0001
   offsets   -0.0060      0.6153   -0.0088      0.0193</code></pre>
</div>
</div>
<div class="body-text-s">
<ul>
<li>In real data, predictors can be correlated. The divergence between SLR and MLR coefficients can be large.</li>
<li>The MLR coefficient reflects the <em>direct</em> effect of each predictor, holding the others constant.</li>
</ul>
</div>
</section>
<section id="section-fstat" class="slide level2" data-menu-title="# Hypothesis testing #" data-background="#047C90">
<h2></h2>
<div class="page-center vertical-center">
<p class="custom-subtitle bottombr">
Hypothesis testing &amp; the F-statistic
</p>
</div>
</section>
<section id="hypotheses-mlr-1" class="slide level2" data-menu-title="All coefficients test in MLR">
<h2></h2>
<p><span class="slide-title">Is any predictor related to the response?</span></p>
<hr>
<p>In SLR: <span class="math inline">\(Y \approx \beta_0 + \beta_1 X\)</span> and we tested</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1=0 \Rightarrow\)</span> no relationship between response and predictor</li>
<li><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\beta_1\neq0 \Rightarrow\)</span> some relationship between response and predictor.</li>
</ul>
<div style="position: absolute; bottom: 370px; right: 1000px; font-size: 1em;">
✏️<br>

</div>
</section>
<section id="hypotheses-mlr" class="slide level2" data-menu-title="All coefficients test in MLR">
<h2></h2>
<p><span class="slide-title">Is any predictor related to the response?</span></p>
<hr>
<p>In SLR: <span class="math inline">\(Y \approx \beta_0 + \beta_1 X\)</span> and we tested</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1=0 \Rightarrow\)</span> no relationship between response and predictor</li>
<li><span class="math inline">\(H_a\)</span>: <span class="math inline">\(\beta_1\neq0 \Rightarrow\)</span> some relationship between response and predictor.</li>
</ul>
<p><br></p>
<p>For MLR: <span class="math inline">\(Y \approx \beta_0 + \beta_1X_1 + \ldots + \beta_p X_p\)</span> and we can test</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 =... =\beta_p=0 \Rightarrow\)</span> no relationship between <span class="math inline">\(Y\)</span> and <em>any</em> predictor <span class="math inline">\(X_1, \ldots, X_p\)</span></li>
<li><span class="math inline">\(H_a\)</span>: at least one <span class="math inline">\(\beta_j \neq 0 \Rightarrow\)</span> some relationship between response and <em>some</em> predictor.</li>
</ul>
<p><br></p>
<p>We are investigating the question <em>Is any predictor related to the response?</em></p>
</section>
<section id="f-statistic-1" class="slide level2" data-menu-title="The F-statistic">
<h2></h2>
<p><span class="slide-title">The F-statistic</span></p>
<hr>
<p>We are investigating the question <em>Is any predictor related to the response?</em></p>
<p>We test this with the <strong><span class="math inline">\(F\)</span>-statistic</strong>:</p>
<p><span class="math display">\[F = \frac{(TSS - RSS)/p}{RSS/(n - p - 1)}\]</span></p>
<div class="body-text-s">
<ul>
<li><span class="math inline">\(TSS = \sum(y_i - \bar{y})^2\)</span> is the total variability in <span class="math inline">\(Y\)</span>,</li>
<li><span class="math inline">\(RSS = \sum(y_i - \hat{y}_i)^2\)</span> is the variability unexplained by the model,</li>
</ul>
</div>
<div style="position: absolute; bottom: 270px; right: 1000px; font-size: 1em;">
✏️<br>

</div>
</section>
<section id="f-statistic" class="slide level2" data-menu-title="The F-statistic">
<h2></h2>
<p><span class="slide-title">The F-statistic</span></p>
<hr>
<p>We are investigating the question <em>Is any predictor related to the response?</em></p>
<p>We test this with the <strong><span class="math inline">\(F\)</span>-statistic</strong>:</p>
<p><span class="math display">\[F = \frac{(TSS - RSS)/p}{RSS/(n - p - 1)}\]</span></p>
<div class="body-text-s">
<ul>
<li><span class="math inline">\(TSS = \sum(y_i - \bar{y})^2\)</span> is the total variability in <span class="math inline">\(Y\)</span>,</li>
<li><span class="math inline">\(RSS = \sum(y_i - \hat{y}_i)^2\)</span> is the variability unexplained by the model,</li>
</ul>
</div>
<div class="body-text-s">
<ul>
<li><em>Numerator</em>: how much variance the predictors collectively explain</li>
<li><em>Denominator</em>: how much variance remains unexplained per degree of freedom</li>
</ul>
</div>
<div class="body-text-s">
<ul>
<li><span class="math inline">\(F \approx 1\)</span>: no predictor is related to <span class="math inline">\(Y\)</span> → consistent with <span class="math inline">\(H_0\)</span></li>
<li><span class="math inline">\(F \gg 1\)</span>: at least one predictor explains variance beyond noise → evidence against <span class="math inline">\(H_0\)</span></li>
</ul>
</div>
<p>An associated <span class="math inline">\(p\)</span>-value is then computed to assess the probability of observing an <span class="math inline">\(F\)</span>-statistic this large or larger, assuming <span class="math inline">\(H_0\)</span> is true.</p>
</section>
<section id="fstat-greenabate" class="slide level2" data-menu-title="F-statistic example">
<h2></h2>
<p><span class="slide-title">Example</span></p>
<hr>
<div id="c23479da" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>   Quantity    Value
F-statistic   612.13
    p-value &lt; 0.0001</code></pre>
</div>
</div>
<p><br></p>
<p>An <span class="math inline">\(F\)</span>-statistic of 612.1 with <span class="math inline">\(p \ll 0.05\)</span> gives very strong evidence that at least one predictor is associated with CO₂ reductions.</p>
<p><br></p>
<div class="fragment">
<div class="teal-text">
<p><strong>Check-in</strong></p>
<p>Pair up with someone.</p>
<p>Have one person explain the hypothesis test for simple linear regression and the other explain the hypothesis test for multiple linear regression.</p>
</div>
</div>
</section>
<section id="hypothesis-testing" class="slide level2" data-menu-title="Hypothesis testing framework">
<h2></h2>
<p><span class="slide-title">Hypothesis testing steps</span></p>
<hr>
<div class="body-text-s">
<p>From EDS 222.</p>
</div>
<div class="body-text-m">
<ol type="1">
<li><p>Identify the TEST STATISTIC</p></li>
<li><p>State your NULL and ALTERNATIVE hypotheses</p></li>
<li><p>Calculate the OBSERVED test statistic</p></li>
<li><p>Estimate the NULL DISTRIBUTION</p></li>
<li><p>Calculate P-VALUE</p></li>
<li><p>Compare p-value to CRITICAL THRESHOLD</p></li>
</ol>
</div>
</section>
<section id="individual-p-values-vs-f-stat" class="slide level2" data-menu-title="Individual p-values">
<h2></h2>
<p><span class="slide-title">Why not just use individual p-values?</span></p>
<hr>
<p>Earlier we saw that each coefficient of the MLR has an associated <span class="math inline">\(p\)</span>-value. So one my ask: why do we need a <span class="math inline">\(p\)</span>-value for the <span class="math inline">\(F\)</span>-statistic, when we can just interpet each <span class="math inline">\(p\)</span>-value individually?</p>
<div class="fragment">
<p>For an individual coefficient, a <span class="math inline">\(p\)</span>-value of 0.05 means:</p>
<blockquote>
<p>“if there is truly no relationship (<span class="math inline">\(H_0\)</span> true), there is a 5% probability of getting a <span class="math inline">\(t\)</span>-statistic this extreme just by random chance.”</p>
</blockquote>
<p>Suppose <span class="math inline">\(p=100\)</span> and there’s truly no association between any predictor and the response. We would expect about 5% of our <span class="math inline">\(t\)</span>-statistics to be “false positives” just by random chance.</p>
</div>
<div class="fragment">
<p>When <span class="math inline">\(p\)</span> is large, we run the risk of some individual <span class="math inline">\(p\)</span>-values being small <em>by chance</em> even when no predictor is truly related to <span class="math inline">\(Y\)</span>.</p>
<p>The <span class="math inline">\(F\)</span>-statistic tests all coefficients jointly and accounts for this.</p>
</div>
</section>
<section id="section-modelfit" class="slide level2" data-menu-title="# Model fit #" data-background="#047C90">
<h2></h2>
<div class="page-center vertical-center">
<p class="custom-subtitle bottombr">
Model fit: R² and adjusted R²
</p>
</div>
</section>
<section id="r2-mlr" class="slide level2" data-menu-title="R² in MLR">
<h2></h2>
<p><span class="slide-title"><span class="math inline">\(R^2\)</span> in multiple regression</span></p>
<hr>
<p>The <span class="math inline">\(R^2\)</span> formula is the same as in SLR:</p>
<p><span class="math display">\[R^2 = 1 - \frac{RSS}{TSS}\]</span></p>
<p>It measures the proportion of variance in <span class="math inline">\(Y\)</span> explained by the model.</p>
<p><br></p>
<p><strong>Important</strong>: adding a predictor to an MLR model will increase <span class="math inline">\(R^2\)</span> or leave it unchanged, even if that predictor has no real relationship with <span class="math inline">\(Y\)</span>.</p>
<div class="fragment">
<p><br></p>
<p>The <strong>adjusted <span class="math inline">\(R^2\)</span></strong> penalizes for the number of predictors:</p>
<p><span class="math display">\[\bar{R}^2 = 1 - \frac{RSS/(n-p-1)}{TSS/(n-1)}\]</span></p>
<p>Adjusted <span class="math inline">\(R^2\)</span> can decrease when an irrelevant predictor is added. Better for comparing models of different sizes.</p>
</div>
</section>
<section id="r2-comparison" class="slide level2" data-menu-title="Check-in: R² SLR vs MLR">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<div id="f9828f4f" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>                     Model    R² Adj. R²
        SLR (process only) 0.611   0.609
MLR (all three predictors) 0.904   0.902</code></pre>
</div>
</div>
<p><br></p>
<div class="teal-text">
<ol type="1">
<li><span class="math inline">\(R^2\)</span> increased when going from SLR to MLR. Does this mean the MLR is a better model?</li>
<li>The adjusted <span class="math inline">\(R^2\)</span> also increased. What does this tell us?</li>
</ol>
</div>
<div class="fragment">
<ol type="1">
<li><p>Probably, but remember <span class="math inline">\(R^2\)</span> always increases (or stays flat) when predictors are added, even useless ones. It cannot be used alone to compare models of different sizes.</p></li>
<li><p>Adjusted <span class="math inline">\(R^2\)</span> penalizes for each extra predictor. The fact that it also increased means <code>efficiency</code> (and possibly <code>offsets</code>) are contributing enough to justify their inclusion.</p></li>
</ol>
</div>
</section>
<section id="section-varsel" class="slide level2" data-menu-title="# Variable selection #" data-background="#047C90">
<h2></h2>
<div class="page-center vertical-center">
<p class="custom-subtitle bottombr">
Variable selection
</p>
</div>
</section>
<section id="varsel-problem" class="slide level2" data-menu-title="The variable selection problem">
<h2></h2>
<p><span class="slide-title">Which predictors should we include?</span></p>
<hr>
<p>With <span class="math inline">\(p\)</span> predictors there are <span class="math inline">\(2^p\)</span> possible ways of choosing which predictors to use:</p>
<ul>
<li><span class="math inline">\(p = 3\)</span>: 8 models,feasible to compare exhaustively</li>
<li><span class="math inline">\(p = 10\)</span>: 1,024 models</li>
<li><span class="math inline">\(p = 30\)</span>: over 1 billion models, completely infeasible</li>
</ul>
<p><br></p>
<div class="fragment">
<p>Three common automated approaches for large <span class="math inline">\(p\)</span>:</p>
<ul>
<li><span class="teal-text"><strong>Forward selection</strong></span>: start with nothing, add one predictor at a time</li>
<li><span class="teal-text"><strong>Backward selection</strong></span>: start with everything, remove one at a time</li>
<li><span class="teal-text"><strong>Mixed selection</strong></span>: combine forward and backward steps</li>
</ul>
</div>
</section>
<section id="forward-backward-1" class="slide level2" data-menu-title="Forward and backward selection">
<h2></h2>
<p><span class="slide-title">Forward and backward selection</span></p>
<hr>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Forward selection</strong></p>
<ol type="1">
<li>Start: null model (intercept only)</li>
<li>Add the predictor with the largest RSS reduction</li>
<li>Repeat until some stopping criterion is met</li>
</ol>
<p>✓ Always applicable</p>
<p>✗ A variable added early may become redundant later</p>
</div><div class="column" style="width:50%;">

</div></div>
</section>
<section id="forward-backward-2" class="slide level2" data-menu-title="Forward and backward selection">
<h2></h2>
<p><span class="slide-title">Forward and backward selection</span></p>
<hr>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Forward selection</strong></p>
<ol type="1">
<li>Start: null model (intercept only)</li>
<li>Add the predictor with the largest RSS reduction</li>
<li>Repeat until some stopping criterion is met</li>
</ol>
<p>✓ Always applicable</p>
<p>✗ A variable added early may become redundant later</p>
</div><div class="column" style="width:50%;">
<p><strong>Backward selection</strong></p>
<ol type="1">
<li>Start: full model (all <span class="math inline">\(p\)</span> predictors)</li>
<li>Remove the predictor with the largest <span class="math inline">\(p\)</span>-value</li>
<li>Repeat until all remaining predictors are significant</li>
</ol>
<p>✓ Considers all predictors from the start</p>
<p>✗ Cannot be used when <span class="math inline">\(p &gt; n\)</span></p>
</div></div>
<p>Can be run using other metrics instead of RSS or <span class="math inline">\(p\)</span>-values.</p>
</section>
<section id="all-8-models-1" class="slide level2" data-menu-title="Check-on">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<div class="columns">
<div class="column" style="width:50%;">
<div id="e36c63c2" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>                    Predictors    RSS
              (intercept only) 5016.8
                       process 1950.3
                    efficiency 3601.4
                       offsets 5010.4
          process + efficiency  497.5
             process + offsets 1949.8
          efficiency + offsets 3571.4
process + efficiency + offsets  483.8</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><strong>Forward selection process</strong></p>
<ol type="1">
<li>Start: null model (intercept only)</li>
<li>Add the predictor with the largest RSS reduction</li>
<li>Repeat until some stopping criterion is met</li>
</ol>
</div></div>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="teal-text">
<p>Trace through forward selection using this table.</p>
<ul>
<li><p>Which predictor would be added first? Second? Does adding <code>offsets</code> meaningfully reduce RSS?</p></li>
<li><p>What criteria could be used to decide whether to add or not the final predictor?</p></li>
</ul>
</div>
</div><div class="column" style="width:50%;">

</div></div>
</section>
<section id="all-8-models-2" class="slide level2" data-menu-title="Check-on">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<div class="columns">
<div class="column" style="width:50%;">
<div id="c8581a39" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>                    Predictors    RSS
              (intercept only) 5016.8
                       process 1950.3
                    efficiency 3601.4
                       offsets 5010.4
          process + efficiency  497.5
             process + offsets 1949.8
          efficiency + offsets 3571.4
process + efficiency + offsets  483.8</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><strong>Forward selection process</strong></p>
<ol type="1">
<li>Start: null model (intercept only)</li>
<li>Add the predictor with the largest RSS reduction</li>
<li>Repeat until some stopping criterion is met</li>
</ol>
</div></div>
<p><br></p>
<div class="columns">
<div class="column" style="width:50%;">
<div class="teal-text">
<p>Trace through forward selection using this table.</p>
<ul>
<li><p>Which predictor would be added first? Second? Does adding <code>offsets</code> meaningfully reduce RSS?</p></li>
<li><p>What criteria could be used to decide whether to add or not the final predictor?</p></li>
</ul>
</div>
</div><div class="column" style="width:50%;">
<ul>
<li><code>process</code> is added 1st (lowest RSS)</li>
<li><code>efficiency</code> is added 2nd: Substantial RSS reduction, <code>efficiency</code> spending is genuinely associated with CO₂ reductions.</li>
<li>Adding <code>offsets</code> to the two-predictor model produces only a very small reduction in RSS</li>
<li>A minimum RSS reduction at each step.</li>
</ul>
</div></div>
</section>
<section id="backward-checkin" class="slide level2" data-menu-title="Check-in: backward selection">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Step 1 — full model</strong></p>
<div id="7edf39cf" class="cell" data-execution_count="14">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor  p-value
   process &lt; 0.0001
efficiency &lt; 0.0001
   offsets   0.0193</code></pre>
</div>
</div>
<p><strong>Step 2 — after first removal</strong></p>
<div id="01888e02" class="cell" data-execution_count="15">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor  p-value
   process &lt; 0.0001
efficiency &lt; 0.0001</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><strong>Backward selection</strong></p>
<ol type="1">
<li>Start: full model (all <span class="math inline">\(p\)</span> predictors)</li>
<li>Remove the predictor with the largest <span class="math inline">\(p\)</span>-value</li>
<li>Repeat until all remaining predictors are significant</li>
</ol>
<p><br></p>
<div class="teal-text">
<p>Using the <span class="math inline">\(p\)</span>-value tables, trace through backward selection step by step.</p>
<ul>
<li>Which predictor is removed first? Why?</li>
<li>Should we remove another predictor in step 2, or stop?</li>
</ul>
</div>
</div></div>
</section>
<section id="backward-checkin-ans" class="slide level2" data-menu-title="Check-in: backward selection">
<h2></h2>
<p><span class="slide-title">Check-in</span></p>
<hr>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Step 1 — full model</strong></p>
<div id="7b29ab0d" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor  p-value
   process &lt; 0.0001
efficiency &lt; 0.0001
   offsets   0.0193</code></pre>
</div>
</div>
<p><strong>Step 2 — after first removal</strong></p>
<div id="bf2c68c2" class="cell" data-execution_count="17">
<div class="cell-output cell-output-stdout">
<pre><code> Predictor  p-value
   process &lt; 0.0001
efficiency &lt; 0.0001</code></pre>
</div>
</div>
</div><div class="column" style="width:50%;">
<p><strong>Backward selection</strong></p>
<ol type="1">
<li>Start: full model (all <span class="math inline">\(p\)</span> predictors)</li>
<li>Remove the predictor with the largest <span class="math inline">\(p\)</span>-value</li>
<li>Repeat until all remaining predictors are significant</li>
</ol>
<p><br></p>
<ul>
<li><strong>Step 1</strong>: <code>offsets</code> has by far the largest <span class="math inline">\(p\)</span>-value → remove it</li>
<li><strong>Step 2</strong>: both <code>process</code> and <code>efficiency</code> have very small <span class="math inline">\(p\)</span>-values → all remaining predictors are significant; stop</li>
</ul>
</div></div>
</section>
<section id="mixed-selection" class="slide level2" data-menu-title="Mixed selection">
<h2></h2>
<p><span class="slide-title">Mixed selection</span></p>
<hr>
<p><strong>Mixed selection</strong> (stepwise) combines forward and backward steps:</p>
<p><br></p>
<ol type="1">
<li>Start with the null model</li>
<li><em>Forward step</em>: add the variable with the largest RSS reduction</li>
<li><em>Backward step</em>: check if any included variable now has a large <span class="math inline">\(p\)</span>-value. If so, remove it</li>
<li>Continue until all variables in the model have sufficiently low <span class="math inline">\(p\)</span>-value, and all variables outside the model would have a large <span class="math inline">\(p\)</span>-value if added.</li>
</ol>
<p><br></p>
<p>This fixes the main weakness of forward selection: a variable added early can be <em>removed</em> once other, better variables are in the model.</p>
</section>
<section id="varsel-in-practice" class="slide level2" data-menu-title="Variable selection: in practice">
<h2></h2>
<p><span class="slide-title">Variable selection: in practice</span></p>
<hr>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Forward can be useful when:</strong></p>
<ul>
<li><span class="math inline">\(p\)</span> is large or <span class="math inline">\(p &gt; n\)</span>. Backward requires fitting the full model, which cannot be done if <span class="math inline">\(p&gt;n\)</span>.</li>
<li>You expect only a few predictors to matter.</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Backward can be useful when:</strong></p>
<ul>
<li><span class="math inline">\(p\)</span> is small and <span class="math inline">\(n\)</span> is large enough to fit the full model</li>
<li>Worry about missing a predictor that only becomes significant in the presence of others.</li>
</ul>
</div></div>
<p><strong>In practice:</strong></p>
<ul>
<li>Mixed selection hedges against the weaknesses of both</li>
<li>Practitioners may run all three and check whether they agree</li>
<li>If all three disagree, that signals correlated predictors and no single “right” model</li>
</ul>
<div class="teal-text body-text-s">
<p>We will later talk about <strong>regularization</strong> (lasso, ridge) over stepwise selection. These methods perform variable selection and coefficient estimation simultaneously and have better statistical properties.</p>
</div>
</section>
<section id="recap" class="slide level2" data-menu-title="Recap">
<h2></h2>
<p><span class="slide-title">In this lesson we covered</span></p>
<hr>
<ul>
<li><strong>MLR model</strong>: <span class="math inline">\(Y = \beta_0 + \beta_1 X_1 + \cdots + \beta_p X_p + \epsilon\)</span> — coefficients interpreted <em>holding all else constant</em></li>
<li>Least squares minimizes RSS</li>
<li><strong>Individual p-values</strong>: test partial effects (does <span class="math inline">\(X_j\)</span> add beyond the others?)</li>
<li><strong>F-statistic</strong>: tests <span class="math inline">\(H_0: \beta_1 = \cdots = \beta_p = 0\)</span></li>
<li><strong><span class="math inline">\(R^2\)</span></strong> always increases with predictors; use <strong>adjusted <span class="math inline">\(R^2\)</span></strong> to compare models of different sizes</li>
<li><strong>Variable selection</strong>: forward, backward, mixed</li>
</ul>
<div class="teal-text">
<p>There are may be many potential problems when we try to fit a linear model to our data.</p>
<p>You will be exploring some of the most common ones in homework 2.</p>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
                // target, if specified
                link.setAttribute("target", "_blank");
                if (link.getAttribute("rel") === null) {
                  link.setAttribute("rel", "noopener");
                }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>