{
  "hash": "35f9129c8e817270d4198b94f356647b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nformat:\n    revealjs:\n        theme: ../../styles/meds-slides-styles.scss\n        slide-number: true\n        chalkboard: true\n        title-slide: false\njupyter: eds232-env\n---\n\n\n\n## {#title-slide data-menu-title=\"Title Slide\" background=\"#053660\"}\n\n[EDS 232]{.custom-title}\n\n<hr class=\"hr-teal\">\n\n[Lesson 4]{.custom-subtitle}\n\n[*Multiple linear regression*]{.custom-subtitle}\n\n---\n\n## {#in-this-lesson data-menu-title=\"In this lesson\"}\n\n[In this lesson]{.slide-title}\n\n<hr>\n\n<br>\n\n- The multiple linear regression (MLR) model\n- Estimating coefficients with least squares\n- Individual $p$-values: partial effects\n- Comparing MLR to individual SLRs\n- Hypothesis testing: the $F$-statistic\n- Model fit: $R^2$ in MLR and adjusted $R^2$\n- Variable selection: forward, backward, and mixed\n\n---\n\n## {#section-mlr data-menu-title=\"# The MLR model #\" background=\"#047C90\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">The multiple linear regression model</p>\n</div>\n\n---\n\n## {#mlr-motivation data-menu-title=\"From SLR to MLR\"}\n\n[From SLR to MLR]{.slide-title}\n\n<hr>\n\nIn SLR we modelled the relationship between **one** predictor and a response:\n\n$$\\texttt{co2\\_reduction} \\approx \\hat{\\beta}_0 + \\hat{\\beta}_1 \\cdot \\texttt{process}$$\n\n. . .\n\n<br>\n\nBut the GreenAbate dataset has **three** potential predictors. Running separate SLRs has two problems:\n\n::: {.body-text-m}\n- No single prediction combining all three predictors\n- Each SLR ignores the other predictors — coefficients can be misleading when predictors are correlated\n:::\n\n. . .\n\n<br>\n\n::: {.center-text .teal-text .body-text-m}\n**Multiple linear regression** handles all predictors simultaneously.\n:::\n\n---\n\n## {#mlr-model data-menu-title=\"The MLR model\"}\n\n[The MLR model]{.slide-title}\n\n<hr>\n\nWith $p$ predictors $X_1, \\ldots, X_p$ and response $Y$:\n\n$$Y = \\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\cdots + \\beta_p X_p + \\epsilon$$\n\n. . .\n\n<br>\n\n::: {.body-text-m}\nThe key phrase in interpreting each coefficient:\n\n> *$\\hat{\\beta}_j$ is the average change in $Y$ associated with a one-unit increase in $X_j$, **holding all other predictors constant**.*\n:::\n\n. . .\n\n<br>\n\nFor GreenAbate ($p = 3$):\n\n$$\\texttt{co2\\_reduction} = \\beta_0 + \\beta_1 \\cdot \\texttt{process} + \\beta_2 \\cdot \\texttt{efficiency} + \\beta_3 \\cdot \\texttt{offsets} + \\epsilon$$\n\n---\n\n## {#mlr-fit data-menu-title=\"MLR fitted coefficients\"}\n\n[Fitted MLR coefficients for GreenAbate]{.slide-title}\n\n<hr>\n\n::: {#d26a3d57 .cell execution_count=2}\n\n::: {.cell-output .cell-output-stdout}\n```\n           Coefficient Std. error t-statistic  p-value\n Intercept      3.4543     0.3416       10.11 < 0.0001\n   process      0.0461     0.0013       35.37 < 0.0001\nefficiency      0.1831     0.0075       24.37 < 0.0001\n   offsets     -0.0088     0.0037       -2.36   0.0193\n```\n:::\n:::\n\n\n. . .\n\n<br>\n\n::: {.body-text-m}\nThe fitted model is:\n\n$$\\widehat{\\texttt{co2}} = 3\\.454 + 0\\.0461 \\cdot \\texttt{process} + 0\\.1831 \\cdot \\texttt{efficiency} \\-0\\.0088 \\cdot \\texttt{offsets}$$\n:::\n\n---\n\n## {#checkin-mlr-interp data-menu-title=\"Check-in: MLR coefficients\" background=\"#053660\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Check-in</p>\n<p class=\"custom-subtitle3\">What is the interpretation of the `efficiency` coefficient of 0\\.1831?</p>\n<p class=\"custom-subtitle3\">A firm spends \\$100K on process, \\$20K on efficiency, \\$50K on offsets. What is the predicted CO₂ reduction?</p>\n</div>\n\n---\n\n## {#checkin-mlr-answers data-menu-title=\"Check-in: MLR answers\" background=\"#053660\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Check-in — answers</p>\n<p class=\"custom-subtitle3\">Each additional \\$1K in efficiency upgrades is associated with 0\\.1831 ktCO₂e of additional CO₂ reduction, <em>holding process and offset spending constant</em>.</p>\n<p class=\"custom-subtitle3\">$\\hat{y} = 3\\.454 + 0\\.0461 \\times 100 + 0\\.1831 \\times 20 \\-0\\.0088 \\times 50 \\approx 11\\.29$ ktCO₂e</p>\n</div>\n\n---\n\n## {#section-pvalues data-menu-title=\"# p-values for coefficients #\" background=\"#047C90\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">p-values for the coefficients</p>\n</div>\n\n---\n\n## {#pvalues-mlr data-menu-title=\"Individual p-values in MLR\"}\n\n[Individual $p$-values: partial effects]{.slide-title}\n\n<hr>\n\nIn SLR, the $p$-value for $\\hat{\\beta}_1$ tests $H_0: \\beta_1 = 0$ — is $X$ related to $Y$?\n\n. . .\n\n<br>\n\nIn MLR, the $p$-value for each $\\hat{\\beta}_j$ tests the **partial effect** of $X_j$:\n\n::: {.center-text .body-text-m .teal-text}\n*Does $X_j$ add information beyond what the other predictors already explain?*\n:::\n\n. . .\n\n<br>\n\n::: {.body-text-m}\n- Small $p$-value for $\\hat{\\beta}_j$ → $X_j$ is informative **given the other predictors are in the model**\n- Large $p$-value for $\\hat{\\beta}_j$ → $X_j$ adds little beyond what the others already capture\n:::\n\n---\n\n## {#checkin-offsets-pvalue data-menu-title=\"Check-in: offsets p-value\" background=\"#053660\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Check-in</p>\n<p class=\"custom-subtitle3\">The `offsets` variable has a p-value of 0\\.0193 in the MLR.</p>\n<p class=\"custom-subtitle3\">Does this mean carbon offset purchases have no relationship with CO₂ reductions?</p>\n<p class=\"custom-subtitle3\">What exactly does this p-value tell us?</p>\n</div>\n\n---\n\n## {#checkin-offsets-answers data-menu-title=\"Check-in: offsets answers\" background=\"#053660\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Check-in — answers</p>\n<p class=\"custom-subtitle3\">Not necessarily. A large p-value means `offsets` adds little <em>beyond what `process` and `efficiency` already explain</em>.</p>\n<p class=\"custom-subtitle3\">In a separate SLR of `co2_reduction` on `offsets` alone, the result could differ.</p>\n<p class=\"custom-subtitle3\">Here, the true coefficient for `offsets` is $-0.001$ (near zero), so the model is correctly detecting it contributes almost nothing.</p>\n</div>\n\n---\n\n## {#section-comparison data-menu-title=\"# MLR vs. individual SLRs #\" background=\"#047C90\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Comparing MLR to individual SLRs</p>\n</div>\n\n---\n\n## {#slr-vs-mlr data-menu-title=\"SLR vs. MLR coefficients\"}\n\n[SLR vs. MLR: why not run separate regressions?]{.slide-title}\n\n<hr>\n\n::: {#5630eef9 .cell execution_count=3}\n\n::: {.cell-output .cell-output-stdout}\n```\n Predictor SLR coeff SLR p-value MLR coeff MLR p-value\n   process    0.0460    < 0.0001    0.0461    < 0.0001\nefficiency    0.1793    < 0.0001    0.1831    < 0.0001\n   offsets   -0.0060      0.6153   -0.0088      0.0193\n```\n:::\n:::\n\n\n. . .\n\n<br>\n\n::: {.body-text-m}\n- In this dataset, SLR ≈ MLR coefficients — because the predictors were drawn independently (uncorrelated by construction).\n- In real data, predictors are typically correlated. The divergence can be large, sometimes **reversing the sign** of a coefficient.\n- The MLR coefficient reflects the *direct* effect of each predictor, holding the others constant.\n:::\n\n---\n\n## {#section-fstat data-menu-title=\"# Hypothesis testing #\" background=\"#047C90\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Hypothesis testing: the F-statistic</p>\n</div>\n\n---\n\n## {#hypotheses-mlr data-menu-title=\"Overall test in MLR\"}\n\n[Is any predictor related to the response?]{.slide-title}\n\n<hr>\n\nIn SLR we tested $H_0: \\beta_1 = 0$. In MLR, the overall question is:\n\n$$H_0: \\beta_1 = \\beta_2 = \\cdots = \\beta_p = 0$$\n$$H_a: \\text{at least one } \\beta_j \\neq 0$$\n\n. . .\n\n<br>\n\nWe test this with the **$F$-statistic**:\n\n$$F = \\frac{(TSS - RSS)/p}{RSS/(n - p - 1)}$$\n\n. . .\n\n::: {.body-text-m}\n- $F \\approx 1$: no predictor is related to $Y$ (consistent with $H_0$)\n- $F \\gg 1$: at least one predictor explains variance beyond noise → evidence against $H_0$\n:::\n\n---\n\n## {#fstat-greenabate data-menu-title=\"F-statistic: GreenAbate\"}\n\n[F-statistic for the GreenAbate MLR]{.slide-title}\n\n<hr>\n\n::: {#5d41c2ba .cell execution_count=4}\n\n::: {.cell-output .cell-output-stdout}\n```\n   Quantity    Value\nF-statistic   612.13\n    p-value < 0.0001\n```\n:::\n:::\n\n\n. . .\n\n<br>\n\n::: {.body-text-m}\nAn $F$-statistic of 612\\.1 with $p \\ll 0.05$ gives very strong evidence that at least one predictor is associated with CO₂ reductions.\n:::\n\n. . .\n\n<br>\n\n**Why not just use the individual p-values?**\n\nWhen $p$ is large, some individual p-values will be small *by chance* even when no predictor is truly related to $Y$. With $p = 100$ truly null predictors, we expect ~5 to have $p < 0.05$ by random chance alone. The $F$-statistic tests all coefficients jointly and accounts for this.\n\n---\n\n## {#section-modelfit data-menu-title=\"# Model fit #\" background=\"#047C90\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Model fit: R² in MLR</p>\n</div>\n\n---\n\n## {#r2-mlr data-menu-title=\"R² in MLR\"}\n\n[$R^2$ in multiple regression]{.slide-title}\n\n<hr>\n\nThe $R^2$ formula is the same as in SLR:\n\n$$R^2 = 1 - \\frac{RSS}{TSS}$$\n\n. . .\n\n<br>\n\n::: {.body-text-m .teal-text}\n**Important caveat:** adding a predictor to an MLR model will **always** increase $R^2$ (or leave it unchanged), even if that predictor has no real relationship with $Y$.\n:::\n\n. . .\n\n<br>\n\nThe **adjusted $R^2$** penalizes for the number of predictors:\n\n$$\\bar{R}^2 = 1 - \\frac{RSS/(n-p-1)}{TSS/(n-1)}$$\n\nAdjusted $R^2$ can **decrease** when an irrelevant predictor is added — making it better for comparing models of different sizes.\n\n---\n\n## {#r2-comparison data-menu-title=\"R² comparison: SLR vs MLR\"}\n\n[Comparing SLR and MLR model fit]{.slide-title}\n\n<hr>\n\n::: {#0020a585 .cell execution_count=5}\n\n::: {.cell-output .cell-output-stdout}\n```\n                     Model    R² RSE (ktCO₂e)\n        SLR (process only) 0.611        3.138\nMLR (all three predictors) 0.904        1.571\n```\n:::\n:::\n\n\n. . .\n\n<br>\n\n::: {.body-text-m}\n- $R^2$ increased from 0\\.611 to 0\\.904 — `efficiency` is genuinely predictive.\n- RSE decreased from 3\\.138 to 1\\.571 ktCO₂e — predictions are more accurate with all three predictors.\n:::\n\n---\n\n## {#section-varsel data-menu-title=\"# Variable selection #\" background=\"#047C90\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Variable selection</p>\n</div>\n\n---\n\n## {#varsel-problem data-menu-title=\"The variable selection problem\"}\n\n[Which predictors should we include?]{.slide-title}\n\n<hr>\n\nWith $p$ predictors there are $2^p$ possible subsets:\n\n::: {.body-text-m}\n- $p = 3$: **8 models** — feasible to compare exhaustively\n- $p = 10$: 1,024 models\n- $p = 30$: over 1 billion models — completely infeasible\n:::\n\n. . .\n\n<br>\n\nThree common automated approaches for large $p$:\n\n::: {.body-text-m}\n- [**Forward selection**]{.teal-text}: start with nothing, add one predictor at a time\n- [**Backward selection**]{.teal-text}: start with everything, remove one at a time\n- [**Mixed selection**]{.teal-text}: combine forward and backward steps\n:::\n\n---\n\n## {#all-8-models data-menu-title=\"All 8 GreenAbate models\"}\n\n[RSS for all 8 possible GreenAbate models]{.slide-title}\n\n<hr>\n\n::: {#85ce90d5 .cell execution_count=6}\n\n::: {.cell-output .cell-output-stdout}\n```\n                    Predictors    RSS\n              (intercept only) 5016.8\n                       process 1950.3\n                    efficiency 3601.4\n                       offsets 5010.4\n          process + efficiency  497.5\n             process + offsets 1949.8\n          efficiency + offsets 3571.4\nprocess + efficiency + offsets  483.8\n```\n:::\n:::\n\n\n. . .\n\n<br>\n\n::: {.teal-text .body-text-m}\n**Check-in:** Trace through forward selection using this table.\n\nWhich predictor would be added first? Second? Does adding `offsets` meaningfully reduce RSS?\n:::\n\n---\n\n## {#checkin-forward-sel data-menu-title=\"Check-in: forward selection\" background=\"#053660\"}\n\n<div class=\"page-center vertical-center\">\n<p class=\"custom-subtitle bottombr\">Check-in — forward selection answers</p>\n<p class=\"custom-subtitle3\">Step 1: `process` has the lowest single-predictor RSS → added first.</p>\n<p class=\"custom-subtitle3\">Step 2: `process + efficiency` has lower RSS than `process + offsets` → `efficiency` added second.</p>\n<p class=\"custom-subtitle3\">Step 3: adding `offsets` gives only a tiny further reduction — whether it is included depends on the stopping criterion.</p>\n</div>\n\n---\n\n## {#forward-backward data-menu-title=\"Forward and backward selection\"}\n\n[Forward and backward selection]{.slide-title}\n\n<hr>\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\n**Forward selection**\n\n1. Start: null model (intercept only)\n2. Add the predictor with the largest RSS reduction\n3. Repeat until stopping criterion is met\n\n✓ Always applicable (works when $p > n$)\n\n✗ A variable added early may become redundant later\n:::\n\n::: {.column width=\"50%\"}\n**Backward selection**\n\n1. Start: full model (all $p$ predictors)\n2. Remove the predictor with the largest $p$-value\n3. Repeat until all remaining predictors are significant\n\n✓ Considers all predictors from the start\n\n✗ Cannot be used when $p > n$\n:::\n\n::::\n\n---\n\n## {#mixed-selection data-menu-title=\"Mixed selection\"}\n\n[Mixed selection]{.slide-title}\n\n<hr>\n\n**Mixed selection** (stepwise) combines forward and backward steps:\n\n<br>\n\n::: {.body-text-m}\n1. Start with the null model\n2. **Forward step**: add the variable with the largest RSS reduction\n3. **Backward step**: check if any included variable now has a large $p$-value — if so, remove it\n4. Continue until no variables are added or removed\n:::\n\n. . .\n\n<br>\n\n::: {.body-text-m .teal-text}\nThis fixes the main weakness of forward selection: a variable added early can be *removed* once other, better variables are in the model.\n:::\n\n---\n\n## {#other-metrics data-menu-title=\"Other selection criteria\"}\n\n[Other criteria for variable selection]{.slide-title}\n\n<hr>\n\nRSS alone always favors larger models — use criteria that **penalize complexity**:\n\n<br>\n\n::: {.body-text-m}\n| Criterion | Formula | Goal |\n|-----------|---------|------|\n| Adjusted $R^2$ | $1 - \\frac{RSS/(n-p-1)}{TSS/(n-1)}$ | Maximize |\n| AIC | $n\\log(RSS/n) + 2p$ | Minimize |\n| BIC | $n\\log(RSS/n) + p\\log(n)$ | Minimize |\n| Test MSE (CV) | held-out set error | Minimize |\n:::\n\n. . .\n\n<br>\n\n::: {.body-text-s}\nBIC penalizes extra predictors more heavily than AIC (for $n > 7$), tending to select sparser models. Cross-validation is the most direct approach when the goal is prediction accuracy.\n:::\n\n---\n\n## {#recap data-menu-title=\"Recap\"}\n\n[In this lesson we covered]{.slide-title}\n\n<hr>\n\n- **MLR model**: $Y = \\beta_0 + \\beta_1 X_1 + \\cdots + \\beta_p X_p + \\epsilon$ — coefficients interpreted *holding all else constant*\n- Least squares minimizes RSS; computer solves it\n- **Individual p-values**: test partial effects (does $X_j$ add beyond the others?)\n- **F-statistic**: tests $H_0: \\beta_1 = \\cdots = \\beta_p = 0$ — use before relying on individual p-values\n- **$R^2$** always increases with predictors; use **adjusted $R^2$** to compare models of different sizes\n- **Variable selection**: forward, backward, mixed — use AIC, BIC, adjusted $R^2$, or CV as criteria\n\n",
    "supporting": [
      "3_2_multiple_linear_regression-SLIDES_files"
    ],
    "filters": [],
    "includes": {}
  }
}