{
  "hash": "33e32a4d40213137d1c2aaae33cf994b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: KNN and accuracy metrics\njupyter: eds232-env\n#echo: false\n---\n\n::: {#4d91681d .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport pandas as pd\nfrom sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import (confusion_matrix, precision_score,\n                              recall_score, f1_score, accuracy_score)\n\nplt.style.use('default')\nfig_size_x = 8\nfig_size_y = 4\nplt.rcParams['font.size'] = 10\n\n# ── KelpWatch synthetic dataset ────────────────────────────────────────────────\n# 300 coastal monitoring stations, each characterized by:\n#   temp_anomaly – sea surface temperature anomaly (°C)\n#   nitrate      – nitrate concentration (μmol/L)\n#   upwelling    – whether upwelling was detected (yes / no)\n#   status       – kelp forest condition: 'healthy' or 'degraded'\n#\n# True data-generating model (logistic):\n#   log-odds(healthy) = -0.8 − 1.5·temp_anomaly + 0.10·nitrate + 1.8·upwelling\n# ──────────────────────────────────────────────────────────────────────────────\nnp.random.seed(42)\nn = 300\n\ntemp_anomaly = np.random.normal(0.4, 1.0, n)\nnitrate      = np.random.normal(14, 4, n)\nupwelling    = np.random.binomial(1, 0.5, n)\n\nlog_odds     = -0.8 + (-1.5 * temp_anomaly) + (0.10 * nitrate) + (1.8 * upwelling)\nprob_healthy = 1 / (1 + np.exp(-log_odds))\nstatus_num   = np.random.binomial(1, prob_healthy, n)\nstatus       = np.where(status_num == 1, 'healthy', 'degraded')\n\ndf = pd.DataFrame({\n    'temp_anomaly':    temp_anomaly,\n    'nitrate':         nitrate,\n    'upwelling':       upwelling,\n    'upwelling_label': np.where(upwelling == 1, 'yes', 'no'),\n    'status':          status,\n    'status_num':      status_num,\n})\n\n# Train/test split used throughout this lesson\nX = df[['temp_anomaly', 'nitrate']].values\ny = df['status'].values\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.3, random_state=42, stratify=y\n)\n\n# Decision boundary grid (reused across several plots)\nx1_range = np.linspace(-2, 4, 300)\nx2_range = np.linspace(X[:, 1].min() - 1, X[:, 1].max() + 1, 300)\nxx1, xx2 = np.meshgrid(x1_range, x2_range)\n```\n:::\n\n\n[📊 Slides](4_1_classification-SLIDES.qmd) / [📊 Blank slides](4_1_classification-SLIDES-BLANK.qmd)\n\nIn this lesson we introduce:\n\n- The classification setting and how it differs from regression\n- Nearest Neighbors (KNN) as a simple, intuitive classification method\n- Accuracy assessment for classifiers: the confusion matrix, precision, recall, and $F_1$ score\n- Overfitting in classification and the bias-variance tradeoff for classifiers\n\nThese notes are based on chapters 2.2.3 and 4 of *An Introduction to Statistical Learning with Applications in Python* [@islp_2023]. The example data is synthetic and was generated with the aid of Claude Code for the purpose of this lesson.\n\n## From regression to classification\n\nSo far we have studied regression methods, which assume the response variable is **quantitative**: a number that can take a continuous range of values. In many situations, however, the response is **qualitative** (also called **categorical**): it takes values in one of a discrete set of categories, or *classes*.\n\n**Classifying** means predicting the qualitative response for an observation. Examples from environmental science include:\n\n- Predicting whether a habitat is *healthy* or *degraded* based on environmental conditions\n- Determining whether a water sample *exceeds* or *does not exceed* a contamination threshold\n- Predicting whether a species is *present* or *absent* at a given location\n\n## A guiding example: kelp forest monitoring\n\nIn this lesson we use a synthetic dataset that tracks 300 coastal monitoring stations. For each station we record:\n\n- **`temp_anomaly`** — sea surface temperature anomaly (°C); positive values indicate warmer-than-average conditions\n- **`nitrate`** — nitrate concentration (μmol/L); higher values generally support kelp growth\n- **`status`** — observed kelp forest condition: *healthy* or *degraded*\n\nThe central question is: *can we predict whether a kelp forest site is healthy or degraded from its oceanographic conditions?*\n\n::: {#cell-initial-data-plotting .cell execution_count=2}\n``` {.python .cell-code}\ncolors  = {'healthy': 'steelblue', 'degraded': 'tomato'}\nmarkers = {1: 'o', 0: 's'}\n\nfig, ax = plt.subplots(figsize=(fig_size_x * 0.75, fig_size_y + 0.5))\n\nfor up_val in [1, 0]:\n    for status_val, col in colors.items():\n        mask = (df['upwelling'] == up_val) & (df['status'] == status_val)\n        ax.scatter(\n            df.loc[mask, 'temp_anomaly'], df.loc[mask, 'nitrate'],\n            c=col, s=20, alpha=0.5, edgecolors='none'\n        )\n\n# Legend 1: kelp status (colors)\nstatus_handles = [\n    plt.scatter([], [], c=col, s=50, label=lab)\n    for lab, col in colors.items()\n]\nleg1 = ax.legend(handles=status_handles, title='Status', fontsize=9, loc='upper left')\nax.add_artist(leg1)\n\nax.set_xlabel('Temp. anomaly (°C)')\nax.set_ylabel('Nitrate (μmol/L)')\nax.set_title(\n    'KelpWatch: kelp status vs. oceanographic conditions\\n'\n    '*Synthetic data generated for educational purposes only*'\n)\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\nplt.close()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_1_knn_accuracy_metrics-NOTES_files/figure-html/initial-data-plotting-output-1.png){#initial-data-plotting width=589 height=442}\n:::\n:::\n\n\n## K-Nearest Neighbors (KNN)\n\n**K-Nearest Neighbors (KNN)** is one of the simplest classification methods. The intuition is straightforward: classify a new observation by majority vote among its nearest neighbors in the training data.\n\n\n### The algorithm\n\nGiven a training set and a new test observation $x_0$:\n\n1. Choose an integer $K \\geq 1$.\n2. **Identify the $K$ points** in the training data that are closest to $x_0$ (typically using Euclidean distance).\n3. **Identify the majority class** among those $K$ nearest neighbors.\n4. **Assign that majority class** as the predicted class for $x_0$.\n\n::: {#cell-knn-illustration .cell execution_count=3}\n``` {.python .cell-code}\n# Small illustrative dataset for the manual KNN exercise\nnp.random.seed(14)\nn_ill = 18\nx1_ill = np.random.uniform(0.5, 5.5, n_ill)\nx2_ill = np.random.uniform(0.5, 5.5, n_ill)\n# healthy = 1 roughly in the upper-left; degraded = 0 roughly lower-right\ny_ill = ((-0.8 * x1_ill + x2_ill + np.random.normal(0, 0.5, n_ill)) > 0.5).astype(int)\ny_ill_label = np.where(y_ill == 1, 'healthy', 'degraded')\n\n# Test point\nx0 = np.array([2.8, 2.8])\n\n# K = 3 neighborhood\ndists  = np.sqrt((x1_ill - x0[0])**2 + (x2_ill - x0[1])**2)\nk3_idx = np.argsort(dists)[:3]\nradius = dists[k3_idx[-1]] + 0.07\n\nfig, ax = plt.subplots(figsize=(4.5, 4.5))\n\ncol_map = {'healthy': 'steelblue', 'degraded': 'tomato'}\nfor label, col in col_map.items():\n    mask = y_ill_label == label\n    ax.scatter(x1_ill[mask], x2_ill[mask], c=col, s=90,\n               edgecolors='k', linewidths=0.6, label=label, zorder=3)\n\nax.scatter(*x0, c='gold', s=200, marker='*', edgecolors='k',\n           linewidths=0.8, label='test point $x_0$', zorder=4)\n\ncircle = plt.Circle(x0, radius, color='dimgray', fill=False,\n                    linestyle='--', linewidth=1.8, label='K = 3 neighborhood')\nax.add_patch(circle)\n\nax.set_xlim(0, 6)\nax.set_ylim(0, 6)\nax.set_xlabel('Temp. anomaly (normalized)')\nax.set_ylabel('Nitrate (normalized)')\nax.legend(fontsize=8, loc='upper left')\nax.set_title('KNN illustration (K = 3)')\nax.set_aspect('equal')\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\nplt.close()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_1_knn_accuracy_metrics-NOTES_files/figure-html/knn-illustration-output-1.png){#knn-illustration width=418 height=441}\n:::\n:::\n\n\n:::{.callout-tip}\n## Check-in\n\nIn the figure above, the star $\\star$ marks a new test observation $x_0$. The dashed circle encloses its $K = 3$ nearest neighbors.\n\n1. Look at the three points inside the circle. What class would KNN assign to $x_0$?\n2. What would change if we used $K = 1$ instead? \n3. What would change if we used $K=$ number of observations in the training set?\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Discussion\n\n1. We can see that two out of the three training points inside the dashed circle belong to the healthy class (blue points). Since healthy is the majority class within the neighborhood, we predict that the test point $x_0$ is in the healthy class too. \n\n2. With $K = 1$ the prediction is determined entirely by the single closest training point. Highly sensitive to local noise. \n\n3. If we use the whole dataset to compute the vote, we will just assign the majority class to every test point.\n\n<!-- 3. Small $K$: the classifier can capture complex, irregular boundaries but is sensitive to individual training points and prone to overfitting. Large $K$ (high bias, low variance): the boundary is smoother and more stable, but may miss real patterns in the data. This is the same bias-variance tradeoff we saw in regression. -->\n:::\n\n\n### Example\n\nWe now apply KNN to our example data using `temp_anomaly` and `nitrate` as predictors. To do so, we use a 70-30 split in our observations and obtain a training set with 210 points and a test set with 90 points. The plot below shows the training and test sets along with the **decision boundary** learned by KNN with $K = 10$.\n\n::: {#cell-knn-decision-boundary .cell execution_count=4}\n``` {.python .cell-code}\nknn10 = KNeighborsClassifier(n_neighbors=10)\nknn10.fit(X_train, y_train)\n\ngrid_pred = knn10.predict(np.c_[xx1.ravel(), xx2.ravel()]).reshape(xx1.shape)\ngrid_num  = (grid_pred == 'healthy').astype(int)\n\ncol_map  = {'healthy': 'steelblue', 'degraded': 'tomato'}\ndatasets = [('Training data', X_train, y_train), ('Test data', X_test, y_test)]\n\nfig, axes = plt.subplots(2, 1, figsize=(fig_size_x * 0.7, (fig_size_y + 0.5) * 1.4), sharex=True)\n\nfor ax, (title, X_data, y_data) in zip(axes, datasets):\n    ax.contourf(xx1, xx2, grid_num, alpha=0.15,\n                cmap='coolwarm_r', levels=[-0.5, 0.5, 1.5])\n    ax.contour(xx1, xx2, grid_num, colors='gray', linewidths=1.2, levels=[0.5])\n    for label, col in col_map.items():\n        mask = y_data == label\n        ax.scatter(X_data[mask, 0], X_data[mask, 1],\n                   c=col, s=20, alpha=0.7, label=label, edgecolors='none')\n    ax.set_xlim(-2, 4)\n    ax.set_ylabel('Nitrate (μmol/L)')\n    ax.set_title(f'KNN (K = 10): {title}')\n    ax.legend(title='True status', fontsize=9)\n    ax.grid(True, alpha=0.3)\n\naxes[1].set_xlabel('Temp. anomaly (°C)')\nplt.tight_layout()\nplt.show()\nplt.close()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_1_knn_accuracy_metrics-NOTES_files/figure-html/knn-decision-boundary-output-1.png){#knn-decision-boundary width=549 height=621}\n:::\n:::\n\n\nThe shaded regions show where the model predicts *healthy* (blue) and *degraded* (red). Points plotted on top are the true labels. A point is misclassified if it appears in the \"wrong\" shaded region.\n\n### Pros and cons of KNN\n\nThere are several pros and cons to using the KNN algorithm:\n\n**Pros:**\n\n- Non-parametric: makes no assumptions about the shape of the decision boundary.\n- Simple and intuitive: there's no explicit model to train, just store the training data.\n- It naturally handles multi-class problems.\n\n**Cons:**\n\n- Slow at prediction time: classifying each new point requires computing its distance to every training point.\n- Sensitive to the scale of predictors: variables with large ranges dominate the distance calculation, so features typically need to be standardized before applying KNN.\n- The choice of $K$ requires cross-validation and has a large impact on performance.\n- Its performance degrades as the number of predictors grows (the *curse of dimensionality*).\n\n<!-- TODO: I would like to include an activity on exercise 4.8-4 in ISLP. -->\n\n## Accuracy assessment for classifiers\n\nTo assess how well a classifier performs, we compare its predictions on the **test set** to the true labels. For a **binary classifier** with two possible classes we call the classes **positive** and **negative**. Given an observation $(x_0, y_0)$ in the test set, we have the following possibilities depending on what prediction was given to $x_0$ and what class $y_0$ it is really associated with:\n\n- **True Positive**: the observation is positive and we correctly predicted positive.\n- **True Negative**: the observation is negative and we correctly predicted negative.\n- **False Positive**: the observation is negative but we incorrectly predicted positive.\n- **False Negative**: the observation is positive but we incorrectly predicted negative.\n\n\n<!-- \n|  | $x_0$ predicted positive | $x_0$ predicted negative |\n|---|---|---|\n| $y_0$ is positive class | True positive | False negative |\n| $y_0$ is negative class | False positive  | True negative  | -->\n\nSo each of our observations in the test set can be classified as true/false positive or true/false negative.\n\n:::{.callout-tip}\n## Check-in\n\nConsider the following predictions for five test observations:\n\n| Observation | True status | Predicted status |\n|---|---|---|\n| A | healthy   | healthy   |\n| B | degraded  | healthy   |\n| C | healthy   | degraded  |\n| D | degraded  | degraded  |\n\nWe will treat healthy as the positive class and degraded as the negative class.\nClassify each observation as true positive, false positive, true negative, or false negative, using `healthy` as the positive class.\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Discussion\n\n- A: True status = healthy (positive), predicted = healthy (positive) → **TP**\n- B: True status = degraded (negative), predicted = healthy (positive) → **FP**\n- C: True status = healthy (positive), predicted = degraded (negative) → **FN**\n- D: True status = degraded (negative), predicted = degraded (negative) → **TN**\n:::\n\n:::{.callout-tip}\n## Check-in\nIdentify one true positive point, one true negative point, one false positive point, and one false negative point. \n\n::: {#cell-identify-points .cell execution_count=5}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(fig_size_x * 0.7, (fig_size_y + 1) * 0.7))\nax.contourf(xx1, xx2, grid_num, alpha=0.15,\n            cmap='coolwarm_r', levels=[-0.5, 0.5, 1.5])\nax.contour(xx1, xx2, grid_num, colors='gray', linewidths=1.2, levels=[0.5])\n\nfor label, col in {'healthy': 'steelblue', 'degraded': 'tomato'}.items():\n    mask = y_test == label\n    ax.scatter(X_test[mask, 0], X_test[mask, 1],\n               c=col, s=25, alpha=0.7, label=label, edgecolors='none')\n\nax.set_xlim(-2, 4)\nax.set_xlabel('Temp. anomaly (°C)')\nax.set_ylabel('Nitrate (μmol/L)')\nax.set_title('KNN decision boundary (K = 10) — test observations shown')\nax.legend(title='True status', fontsize=9)\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\nplt.close()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_1_knn_accuracy_metrics-NOTES_files/figure-html/identify-points-output-1.png){#identify-points width=556 height=341}\n:::\n:::\n\n\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Discussion\nYou may have identified other points, these are some examples!\n\n![](point-classification.png)\n:::\n\n### The confusion matrix\n\nOnce we have predicted the class for every point in our test set and compared it t its true class, we can count the total number of true/false positives and true/false negatives we obtained. We use the notation:\n\n- TP = total number of true positives\n- TN = total number of true negatives\n- FP = total number of false positives\n- FN = total number of false negatives\n\nThese four counts are organized into a **confusion matrix**, which gives a concise summary of where the classifier is correct and what types of errors it makes:\n\n\n|  | Predicted positive | Predicted negative |\n|---|---|---|\n| **True positive** | TP | FN |\n| **True negative** | FP | TN |\n\n\n\n:::{.callout-tip}\n## Check-in\n\nThe confusion matrix for our KNN model is\n\n::: {#confusion-matrix .cell execution_count=6}\n``` {.python .cell-code}\ny_pred = knn10.predict(X_test)\ncm     = confusion_matrix(y_test, y_pred, labels=['healthy', 'degraded'])\nTP, FN, FP, TN = cm[0, 0], cm[0, 1], cm[1, 0], cm[1, 1]\n\ncm_df = pd.DataFrame(\n    [[f'TP = {TP}', f'FN = {FN}'],\n     [f'FP = {FP}', f'TN = {TN}']],\n    index   = ['True: healthy',  'True: degraded'],\n    columns = ['Predicted: healthy', 'Predicted: degraded']\n)\nprint(cm_df.to_string())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Predicted: healthy Predicted: degraded\nTrue: healthy             TP = 49             FN = 11\nTrue: degraded            FP = 20             TN = 10\n```\n:::\n:::\n\n\nUsing the confusion matrix above:\n\n1. How many healthy sites were correctly identified?\n2. How many degraded sites were incorrectly classified as healthy? What type of error is this: false positive or false negative?\n3. From an ecological monitoring perspective, which type of error do you think could be more costly? Why?\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Discussion\n\n1. That is the True Positive count: the top-left cell of the confusion matrix.\n\n2. The bottom-left cell gives the count of degraded sites predicted as healthy, these are False Positives. The classifier declared a site healthy when it was actually degraded.\n\n3. One could argue that False Positives (predicting *healthy* when the site is *degraded*) are likely more costly: a truly degraded site would go undetected and receive no intervention. A False Negative (predicting *degraded* when the site is actually healthy) might trigger unnecessary action, but the ecological harm is lower than missing real degradation. The relative cost always depends on the specific application!\n:::\n\n### Accuracy metrics\n\nGiven the confusion matrix counts, we can compute several summary metrics.\n\n**Overall accuracy** is the fraction of test observations correctly classified:\n\n$$\\text{accuracy} = \\frac{TP + TN}{TP + FP + TN + FN}.$$\n\n**Precision** answers: *of the observations predicted as positive, what fraction are truly positive?* It is given by\n\n$$\\text{precision} = \\frac{TP}{TP + FP}.$$\n\n**Recall** (also called *sensitivity*) answers: *of all the truly positive observations, what fraction did we correctly identify?* It is defined as\n\n$$\\text{recall} = \\frac{TP}{TP + FN}.$$\n\nAll of these accuracy metrics take on values between 0 and 1, with 1 being the highest accuracy and 0 the lowest.\n\n:::{.callout-tip}\n## Check-in\n1. Imagine you use a classifier that always predicts positive. What would recall be like? What about precision?\n2. Imagine you use a classifier that rarely predicts positive but, when it does, it is spot on. What would recall be like? What about precision?\n3. If you are a conservation manager who needs to allocate resources to degraded sites, which metric would you prioritize? \n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Discussion\n1. A classifier that always predicts positive will have *perfect recall* (it never misses a positive) but *low precision* (many of its positive predictions are wrong).\n2. A classifier that rarely predicts positive will have *high precision* (when it does predict positive, it is usually right) but *low recall* (it misses many true positives).\n3. A conservation manager should likely prioritize *recall*: the goal is to correctly identify as many truly degraded sites as possible so they can receive intervention. Missing a degraded site (False Negative) could have direct ecological consequences. \n:::\n\nPrecision and recall capture different aspects of classifier performance and often trade off against each other.\nThe right balance depends on the application and the relative costs of false positives and false negatives.\n\n### The $F_1$ score\n\nWhen we want to summarize both precision and recall in a single number, we can use the **$F_1$ score**, defined as their harmonic mean:\n\n$$F_1 = \\frac{2 \\cdot \\text{precision} \\times \\text{recall}}{\\text{precision} + \\text{recall}}$$\n\nSome properties of the $F_1$ score:\n\n- Ranges from 0 (worst) to 1 (best).\n- It **favors classifiers with balanced precision and recall**: a model with high precision but very low recall (or vice versa) receives a low $F_1$ score.\n- It is a simple way to compare classifiers with one number, but you should always examine precision and recall individually to understand the underlying trade-off.\n\n\n:::{.callout-tip}\n## Check-in\n\nBack in our kelp forest health classification, suppose we also implement a **null classifier** which always predicts the majority class regardless of the predictors. The table below compares all four metrics for the null classifier and the KNN model:\n\n::: {#accuracy-metrics .cell execution_count=7}\n``` {.python .cell-code}\nmajority_class = pd.Series(y_test).value_counts().idxmax()\nnull_preds     = np.full(len(y_test), majority_class)\n\nnull_acc  = accuracy_score(y_test, null_preds)\nnull_prec = precision_score(y_test, null_preds, pos_label='healthy', zero_division=0)\nnull_rec  = recall_score(y_test, null_preds, pos_label='healthy', zero_division=0)\nnull_f1   = f1_score(y_test, null_preds, pos_label='healthy', zero_division=0)\n\nacc  = accuracy_score(y_test, y_pred)\nprec = precision_score(y_test, y_pred, pos_label='healthy')\nrec  = recall_score(y_test, y_pred, pos_label='healthy')\nf1   = f1_score(y_test, y_pred, pos_label='healthy')\n\nmetrics_df = pd.DataFrame({\n    'Model':     ['Null classifier', 'KNN (K = 10)'],\n    'Accuracy':  [f'{null_acc:.3f}',  f'{acc:.3f}'],\n    'Precision': [f'{null_prec:.3f}', f'{prec:.3f}'],\n    'Recall':    [f'{null_rec:.3f}',  f'{rec:.3f}'],\n    'F₁ score':  [f'{null_f1:.3f}',  f'{f1:.3f}'],\n})\nprint(metrics_df.to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Model Accuracy Precision Recall F₁ score\nNull classifier    0.667     0.667  1.000    0.800\n   KNN (K = 10)    0.656     0.710  0.817    0.760\n```\n:::\n:::\n\n\nLooking at the comparison table:\n\n1. The null classifier always predicts *healthy*. Why does it have a recall of 1\\.000 but a lower $F_1$ score?\n2. KNN achieves accuracy 0\\.656 vs. the null's 0\\.667. Is accuracy alone a good summary to assess whether KNN is no better than the null classifier?\n3. Is this KNN model with K=10 good enough or would it be worth it to explore other alternatives?\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Discussion\n\n1. Because the null classifier always predicts *healthy* (positive), it never produces a false negative. Every truly positive site gets predicted as positive, so recall is perfect. However, it also misclassifies every negative site as positive, which drives down precision and therefore $F_1$.\n\n2. No. The two classifiers have similar accuracy (0\\.667 vs. 0\\.656), yet KNN has some evidence of distinguishing between classes rather than blindly predicting the majority. \n\n3. Definitely explore other alternatives!\n:::\n\nThe null classifier is a useful baseline. Its accuracy equals the proportion of the most common class in the test set. Any useful model should outperform this trivial baseline. Looking at precision, recall, and $F_1$ together gives a much fuller picture than accuracy alone.\n\n## Overfitting in classification\n\n\nIn classification we can consdider the overall **error rate** as a simple metric to compare model performance across models:\n\n$$\\text{error rate} = \\frac{\\text{number of misclassified observations}}{\\text{total observations}} = \\frac{FP + FN}{TP + FP + TN + FN}.$$\n\nWe get the **training and test error rates** for a classifier when we calculate the error rate of the classifier on the training and test sets, respectively. \n\nAs in regression, classifiers can also **overfit** the training data. Recall that:\n\n> A model is overfitting when it has a small training error but a large test error. \n\n:::{.callout-tip}\n## Check-in\n\nThe parameter $K$ directly controls the flexibility of the KNN classifier. The plot below shows training and test error across a range of $K$ values. \n\n::: {#cell-train-test-error-curve .cell execution_count=8}\n``` {.python .cell-code}\nk_range      = list(range(1, 151, 2))\ntrain_errors = []\ntest_errors  = []\n\nfor k in k_range:\n    knn_k = KNeighborsClassifier(n_neighbors=k)\n    knn_k.fit(X_train, y_train)\n    train_errors.append(1 - knn_k.score(X_train, y_train))\n    test_errors.append(1 - knn_k.score(X_test,  y_test))\n\nnull_error = 1 - null_acc\n\nfig, ax = plt.subplots(figsize=(fig_size_x, fig_size_y))\nax.plot(k_range, train_errors, 'b-o', markersize=3, label='Training error')\nax.plot(k_range, test_errors,  'r-o', markersize=3, label='Test error')\nax.axhline(null_error, color='gray', linestyle='--', linewidth=1.5,\n           label=f'Null classifier error ({null_error:.3f})')\nax.set_xlabel('K (number of neighbors)')\nax.set_ylabel('Classification error rate')\nax.set_title('KNN: training and test error vs. K')\nax.legend(loc='lower right')\nax.grid(True, alpha=0.3)\nplt.tight_layout()\nplt.show()\nplt.close()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_1_knn_accuracy_metrics-NOTES_files/figure-html/train-test-error-curve-output-1.png){#train-test-error-curve width=789 height=390}\n:::\n:::\n\n\nLooking at the error curves:\n\n1. At $K = 1$, what is the training error and why?\n2. Identify the region of the plot where the classifier is overfitting. What features of the curve indicate this?\n3. Where would you choose $K$ to get the best generalization performance?\n:::\n\n:::{.callout-tip collapse=\"true\"}\n## Discussion\n\n1. At $K = 1$ the training error is 0 . With a single nearest neighbor, every training point's closest neighbor is itself, so it is always classified correctly. This is the clearest possible sign of overfitting.\n\n\n2. Overfitting occurs on the left side of the plot (small $K$). Here training error is very low but test error is notably higher. The gap between the two curves is the signature of overfitting: the model has learned the noise in the training data rather than the true underlying pattern.\n\n3. The best generalization performance is near the value of $K$ where test error is minimized, before it rises again for very large $K$ (where the model underfits). In practice this optimal $K$ is selected via cross-validation rather than by looking at the test set directly.\n:::\n\n### The Bias-Variance tradeoff\n\nRecall  that **model variance** refers to how much our model would change if we trained it on a different data set. \n\nIn the figure below we examine the variance of a KNN classifier with different values of $k$ when applied to two training sets from the same population:\n\n::: {#cell-variance-bias-knn .cell execution_count=9}\n``` {.python .cell-code}\n# Generate a second training set from the same data-generating process\nnp.random.seed(99)\nn2           = len(X_train)\ntemp2        = np.random.normal(0.4, 1.0, n2)\nnit2         = np.random.normal(14, 4, n2)\nup2          = np.random.binomial(1, 0.5, n2)\nlog_odds2    = -0.8 + (-1.5 * temp2) + (0.10 * nit2) + (1.8 * up2)\nprob2        = 1 / (1 + np.exp(-log_odds2))\nstatus2      = np.where(np.random.binomial(1, prob2, n2) == 1, 'healthy', 'degraded')\nX_train2     = np.column_stack([temp2, nit2])\ny_train2     = status2\n\nk_bv       = [1, 30]\ntrain_sets = [('Training set A', X_train,  y_train,  'o'),\n              ('Training set B', X_train2, y_train2, '^')]\ncol_map    = {'healthy': 'steelblue', 'degraded': 'tomato'}\n\nfig, axes = plt.subplots(2, 2,\n                         figsize=(fig_size_x * 0.91, (fig_size_y + 0.5) * 1.4),\n                         sharex=True, sharey=True)\n\nfor row, k in enumerate(k_bv):\n    for col, (set_name, X_tr, y_tr, mkr) in enumerate(train_sets):\n        ax = axes[row, col]\n        knn_bv = KNeighborsClassifier(n_neighbors=k)\n        knn_bv.fit(X_tr, y_tr)\n        gp = knn_bv.predict(np.c_[xx1.ravel(), xx2.ravel()]).reshape(xx1.shape)\n        gn = (gp == 'healthy').astype(int)\n        ax.contourf(xx1, xx2, gn, alpha=0.15, cmap='coolwarm_r', levels=[-0.5, 0.5, 1.5])\n        ax.contour(xx1, xx2, gn, colors='gray', linewidths=1.0, levels=[0.5])\n        for label, c in col_map.items():\n            mask = y_tr == label\n            ax.scatter(X_tr[mask, 0], X_tr[mask, 1],\n                       color=c, marker=mkr, s=12, alpha=0.5, edgecolors='none')\n        ax.set_xlim(-2, 4)\n        ax.set_title(f'K = {k} — {set_name}', fontsize=10)\n        ax.grid(True, alpha=0.2)\n        if col == 0:\n            ax.set_ylabel('Nitrate (μmol/L)')\n        if row == 1:\n            ax.set_xlabel('Temp. anomaly (°C)')\n\nfig.suptitle(\n    'Decision boundaries across two training sets for k=1 and k=30',\n     y=1.02\n)\nplt.tight_layout()\nplt.show()\nplt.close()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_1_knn_accuracy_metrics-NOTES_files/figure-html/variance-bias-knn-output-1.png){#variance-bias-knn width=717 height=647}\n:::\n:::\n\n\n:::{.callout-tip}\n## Check-in\nLooking at the plots above, which value of $K$ do you think gives a model with higher variance? Why?\n:::\n:::{.callout-tip collapse=\"true\"}\n## Discussion\nThe decision boundaries created by both models ($K=1$ and $K=10$) change when trained on different datasets. However, we could say that the $k=1$ KNN model exhibits higher variance since there's a lot of small classiffication regions (fitting noise) that change substantially as we move from training set A to B. \n:::\n\nOn the other hand, **model bias** refers to the error introduced by the assumptions built into the model. Models with high bias will be systematically wrong, no matter how much training data we give it. In our example, when $k$ is really big, all points will be classified as the majority class. If both training sets are sampled from the same popuplation, we expect this model to remain constant across training sets. \n\n::: {#cell-high-bias-knn .cell execution_count=10}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2,\n                         figsize=(fig_size_x * 0.91, (fig_size_y + 0.5) * 0.7),\n                         sharex=True, sharey=True)\n\nk = 120\nfor col, (set_name, X_tr, y_tr, mkr) in enumerate(train_sets):\n    ax = axes[col]\n    knn_bv = KNeighborsClassifier(n_neighbors=k)\n    knn_bv.fit(X_tr, y_tr)\n    gp = knn_bv.predict(np.c_[xx1.ravel(), xx2.ravel()]).reshape(xx1.shape)\n    gn = (gp == 'healthy').astype(int)\n    ax.contourf(xx1, xx2, gn, alpha=0.15, cmap='coolwarm_r', levels=[-0.5, 0.5, 1.5])\n    ax.contour(xx1, xx2, gn, colors='gray', linewidths=1.0, levels=[0.5])\n    for label, c in col_map.items():\n        mask = y_tr == label\n        ax.scatter(X_tr[mask, 0], X_tr[mask, 1],\n                   color=c, marker=mkr, s=12, alpha=0.5, edgecolors='none')\n    ax.set_xlim(-2, 4)\n    ax.set_title(f'K = {k} — {set_name}', fontsize=10)\n    ax.set_xlabel('Temp. anomaly (°C)')\n    ax.grid(True, alpha=0.2)\n    if col == 0:\n        ax.set_ylabel('Nitrate (μmol/L)')\n\nfig.suptitle('Decision boundaries across two training sets', y=1.02)\nplt.tight_layout()\nplt.show()\nplt.close()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_1_knn_accuracy_metrics-NOTES_files/figure-html/high-bias-knn-output-1.png){#high-bias-knn width=717 height=326}\n:::\n:::\n\n\n:::{.callout-tip}\n## Check-in\nWhat do you notice in the decision boundaries? \n:::\n\n\n\nThe same bias-variance tradeoff discussed for regression in [previous notes](/notes/2_2_assessing_model_accuracy/2_2_assessing_model_accuracy-NOTES.qmd) applies here:\n\n- A high flexibility model often shows low bias and high variance. The flexible boundary can capture complex patterns but changes a lot from one training sample to another.\n- A low flexibility model often shows high bias and low variance. The rigid boundary is stable but may systematically miss real structure in the data.\n\nIncreasing model flexibility always reduces training error, but test error has a characteristic U-shape we'd seen previously. \n\n",
    "supporting": [
      "4_1_knn_accuracy_metrics-NOTES_files"
    ],
    "filters": [],
    "includes": {}
  }
}