{
  "hash": "0e4543ebb40506a61a5f3a0cff6d347c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Learning from data\n---\n\n[📊 Slides](2_1_what_is_statistical_learning-SLIDES.qmd) / [📊 Blank slides](2_1_what_is_statistical_learning-SLIDES-BLANK.qmd)\n\n\n\nIn this lesson we introduce:\n\n- The idea of estimating a function $f$ using observed data\n- Inference and prediction\n- Training set = observations used to fit/train a model\n- Predictors + response variable & their math notation\n- Parametric vs. non parametric\n- Regression vs. classification\n- Unsupervised vs. supervised learning\n\nThese notes are based on chapter 2.1 of the book *An Introduction to Statistical Learning with Applications in Python* (James et al., 2023). \n\n## Investigating elephant seal population\n\nAmanda is a marine scientist investigating how protected areas affect the population of elephant seals in California. Specifically, she wants to understand: *how does elephant seal population change in a protected rookery that has just been protected?*\n\n![(Northern Elephant Seals (M. angustirostris) at sunrise early light at Piedras Blancas, San Simeon, CA 03 Feb 2012. Photo by [Mike Baird](https://commons.wikimedia.org/wiki/File:Northern_Elephant_Seals_%28M._angustirostris%29_at_sunrise_early_light_at_Piedras_Blancas,_San_Simeon,_CA.jpg).](images/elephant_seals.jpg)\n\n\nShe identifies the **predictor variable** as time since the rookery was protected and the **response variable** as elephant seal population (since elephant seal population *responds* on time). \n\n::: {#9ce16f66 .cell execution_count=2}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-3-output-1.png){width=711 height=376}\n:::\n:::\n\n\n### An ideal function $f$ exists somewhere, we just can't access it\n\nWhat if Amanda was given the true, real relationship between time and population? \n\nIn mathematical terms, this would mean Amanda would have a **function $f$** such that\n\n $$f(\\text{time since protection}) = \\text{true population}.$$\n\n::: {#f0001783 .cell execution_count=3}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-4-output-1.png){width=711 height=376}\n:::\n:::\n\n\n::: {.callout-tip}\n## Check-in\n\n1. What does $f(0)$ represent? What does $f(5)=100$ mean?\n\n2. What could Amanda do if she had this function $f$?\n:::\n:::{.callout-tip  collapse=\"true\" }\n# Discussion\n\n- She could understand whether and how population and time are related: is there no relation, does it increase, decrease, varies, etc? \n- She could also understand the mathematical form of this relationship: for example, is it linear?\nThese are examples of using the function $f$ for **inference**.\n\n- She could also use the function $f$ to know the elephant seal population in the future, i.e. using the function for **prediction**. In addtion, she could probably save resources spent in going out into the field for data collection. \n:::\n\n### Our next best option is to estimate $f$ using data\n\nClearly Amanda has no access to this true, ideal function! So her next best option is to try to **estimate $f$** using data.\n\nFortunately, she found some long-term ecological data that measures the elephant seal population since the protection for the rookery was established:\n\n::: {#43cfa165 .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-5-output-1.png){width=711 height=376}\n:::\n:::\n\n\nThese are the **observed values** for the response variable. \n\n::: {.callout-tip}\n## Check-in\n\nAre the observed values the \"true values\" for the response variable?\n:::\n\nError can be introduced during measurement. In this case we have\n\n$$f(\\text{time}) = \\text{true population} = \\text{observed population} + \\text{error}$$\n\n::: {#39bd6e57 .cell execution_count=5}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-6-output-1.png){width=711 height=376}\n:::\n:::\n\n\nWith these observed population values at a given time, Amanda can try to estimate the real function $f$ with another **function $\\hat{f}$**. Some estimates of $f$ are shown in the graph below.\n\n::: {#52fc4647 .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-7-output-1.png){width=711 height=392}\n:::\n:::\n\n\n::: {.callout-tip}\n## Check-in\nWhat considerations can Amanda take into account when choosing an estimate $\\hat{f}$?\n:::\n:::{.callout-tip  collapse=\"true\" }\n# Discussion\n\nMany! Preliminary understanding of the data, the application (prediction or inference?), volume of available data, minimizing error, even computing power. Selecting any $\\hat{f}$ comes with tradeoffs!\n:::\n\n## Abstract setup\n\nRoughly, this is the setup in which we will be working in. Let's see it more abstractly:\n\nWe have a set of $p$ **predictors** $X_1, ..., X_p$ and a **dependent variable** $Y$. \n\nWe assume there is a relationship between $Y$ and $X = (X_1, ..., X_p)$ that can be written as \n$$Y = f(X) + \\epsilon.$$\n\nHere $f$ is some fixed but *unknown* function of the predictors $X_1, . . ., X_p$ and $\\epsilon$ represents an error term (independent of $X$ and with mean zero). \n\nOur objective is to estimate $f(X)$ well enough with another function $\\hat{f}(X)$. \n\n### Why bother to estimate $f$? \n\n1. Do **inference**: use $\\hat{f}$ to understand which predictors are associated with the response and understand the form of this relationship. \n\n2. Do **predictions**: this means calculating $\\hat{f}(X) = \\hat{Y}$ to predict what the value of $Y$ will be with at a new input $X$. \n\nDepending whether our goal is prediction, inference, or a combination of the two, we may select different methods for estimating $f$. \n\nGenerally: \n\n- models for $f$ that are interpretable enough to allow inference may not be have as accurate prediction results as other approaches. \n- models for $f$ that can give excellent predictions, may not be as interpretable and make inference more challenging.\n\nThere's a tradeoff. \n\nGenerally, **machine learning** may prioritize predictions over interpretability (we want the best prediction, even if we got it out of a black box), while **statistical modeling** may prioritize interpretability over prediction.\n\n\n:::{.callout-tip}\n## Check-in\n\nWhat are some problems or scenarios where inference may be more important than prediction? What about an problems or scenarios where prediction is the priority?\n:::\n\n### How do we estimate $f$?\n\nWe start with a set of $n$ observed data points:\n\n$$ \\{ (x_1, y_1) , ..., (x_n, y_n)\\}, $$\n\nwhere \n\n- $x_i$ = a *vector* with with the **predictor information**, and \n- $y_i$ = the **response variable** for the $i$-th observation.\n\nThese data points are the **training set** or **training data** because we will use them to **train** (or **fit**) our method and obtain an estimate $\\hat{f}$ of the \"true\" function $f$. \n\nOur goal is to apply methods to the training data to estimate the unknown function $f$ that links predictors with the response.\n\nThe \"learning\" part in *machine learning* is precisely the process of adjusting $\\hat{f}$ to minimize error on the training data.\n\n### Notation \nOur training set has $n$ observed data points: \n\n$$ \\{ (x_1, y_1) , ..., (x_n, y_n)\\}.$$\n\nIf we have $p$ predictors, then each $x_i$ is a **vector** of the form:\n$$x_i = (x_{i1}, ..., x_{ip}).$$\nThe response variable $y_i$ is just a single number or category.\n\nFor example, for our previous data we would transfor the data table into the corresponding notation as shown below. \n\n<!-- table with 4 values of time, population, and something else and then these values represented as vectors x_i and their corresponding value y_i-->\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n| Obs. | Time (Predictor) |  Population (Response)|\n|-------------|------|------------|\n| 1 | 2 | 53 |\n| $\\vdots$ | $\\vdots$ | $\\vdots$ |\n| 5 | 10 | 353 |\n| $\\vdots$ | $\\vdots$ | $\\vdots$ |\n| 9  | 18 | 473 |\n:::\n\n::: {.column width=\"10%\"}\n\\\n\n\\\n\n\\\n\n\\\n\n\\ \\ \\ \\ \\ \\ \\ \\ \\ **→**\n:::\n\n::: {.column width=\"35%\"}\n\\\n\\\n\n$(x_1,y_1) = (2,53)$\n\n$\\vdots$\n\n$(x_5,y_5) = (10,353)$\n\n$\\vdots$\n\n$(x_9,y_9) = (18,473)$\n\n:::\n\n::::\n\nIf we were to add average annual sea surface temperature (SST) as a second predictor variable, then our notation would update accordingly:\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n| Obs. | Time (Predictor 1) | SST (Predictor 2) | Population (Response)|\n|-------------|------|------|------------|\n| 1 | 2 | 17.05| 53 |\n| $\\vdots$ | $\\vdots$ |  $\\vdots$ | $\\vdots$ |\n| 5 | 10 | 20.86 | 353 |\n| $\\vdots$ | $\\vdots$ | $\\vdots$ |  $\\vdots$ |\n| 9  | 18 | 23.27| 473 |\n:::\n\n::: {.column width=\"10%\"}\n\\\n\n\\\n\n\\\n\n\\\n\n\\ \\ \\ \\ \\ \\ \\ \\ \\ **→**\n:::\n\n::: {.column width=\"35%\"}\n\n$x_1 = (x_{1,1}, x_{1,2}) = (2, 17.05)$  \n\n$y_1 = 53$\n\n$\\vdots$\n\n$x_5 = (x_{5,1}, x_{5,2}) = (10, 20.86)$  \n\n$y_5 = 353$\n\n$\\vdots$\n\n$x_9 = (x_{9,1}, x_{9,2}) = (18, 23.27)$ \n\n$y_9 = 473$\n\n:::\n\n::::\n\n## Parametric methods\n\nBroadly, most methods for estimating $f$ can be characterized as parametric or non-parametric. \n\nParametric methods estimate $f$ in two steps:\n\n1. Make an assumption about the *functional form* or shape of $f$.\n\n2. Use the training data to **train** or **fit** the model and get those parameters that will define the estimate $\\hat{f}$. \n\nConsiderations:\n\n- May be used with small training sets\n- May be computationally easier to estimate a few parameters\n- Simpler functional forms for $\\hat{f}$ can make inference easier\n- Assumed functional form for $\\hat{f}$ may be far from true $f$, making predictions inaccurate\n- Predictions could not be as good\n\n\n### Example\n\n1. Amanda *decides* to model the population with a linear model on the predictors $X_1 =$ *time* and $X_2=$ *average annual sea surface temperature (SST)*. This means she assumes the function \n\n$$f(\\text{time}, \\text{SST}) = \\text{population}$$ \n\nhas the form\n\n$$ f(x_1, x_2) = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2. $$\n\n2. She trains the model to get an estimate for $f$, by finding *parameters* $\\beta_0, \\beta_1$, and $\\beta_2$ such that\n\n$$ \\text{observed data} \\approx \\beta_0 + \\beta_1 \\text{time} + \\beta_2 \\text{SST} .$$\n\nThis is great! She only needs to find three numbers to get a model for the population.\n\n::: {#376b5cab .cell execution_count=7}\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear Model: Population = -1112.46 + 10.10*Time + 64.58*SST\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-8-output-2.png){width=603 height=590}\n:::\n:::\n\n\n## Non-parametric methods\n\nNon-parametric methods do not make explicit assumptions about the functional form of $f$. Instead, they seek an estimate of $f$ that gets as close to the training set as possible without being \"being too rough or wiggly\". \n\nConsiderations:\n\n- May be better at prediction\n- May need a lot of data to fit the model\n- May follow errors or noise in the data too closely \n- May be less interpretable than more restrictive models\n\n### Example\n\nInstead of assuming a linear form, Amanda uses **K-nearest neighbors (KNN)** to estimate $f(\\text{time}, \\text{SST})$. For any new combination of time and SST, the model predicts population as the average of the $K$ most similar observations in the training set. No assumptions about the shape of $f$ required.\n\n::: {#994f478f .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-9-output-1.png){width=601 height=590}\n:::\n:::\n\n\nNotice the fitted surface is no longer a flat plane, but it bends and curves to follow the data. Amanda did not specify any functional form; the shape of $\\hat{f}$ emerges entirely from the training observations.\n\n## Regression vs. Classification \n\nVariables can be either:\n\n- **quantitative**: continuous numerical values, or \n\n- **qualitative** or **categorical**: values in one of $K$ different classes or categories. \n\nProblems having a quantitative response are **regression problems**.\n\nProblems having a qualitative response are **classification problems**. \n\nWe tend to select machine learning methods based on whether the response is quantitative or qualitative. \n\nWhat about the predictors being quantitative or categorical? Not as important, often possible to *code* qualitative predictors before the analysis.  \n\n### Example\n\nAmanda wants to predict the **health status** of individual adult seals. A veterinarian has assessed a sample of seals and labeled each one as *healthy*, *malnourished*, or *injured*. Amanda wants to train a classifier using weight and length as predictors:\n\n$$f(\\text{weight, length}) = \\text{health status} \\in \\{\\text{healthy, malnourished, injured}\\}.$$\n\nHer **labeled training data** looks like this:\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n| Obs. | Length (Predictor 1) | Weight (Predictor 2) | Health status (Response)|\n|-------------|------|------|------------|\n| 1 | 173.58 | 200.14| healthy |\n| $\\vdots$ | $\\vdots$ |  $\\vdots$ | $\\vdots$ |\n| 44 | 157.06 | 122.96 | malnourished |\n| $\\vdots$ | $\\vdots$ | $\\vdots$ |  $\\vdots$ |\n| 90  |  163.48 | 164.98 | injured|\n\n: {tbl-colwidths=\"[20,40,40]\"}\n\n:::\n\n::: {.column width=\"10%\"}\n\\\n\n\\\n\n\\\n\n\\\n\n\\ \\ \\ \\ \\ \\ \\ \\ \\ **→**\n:::\n\n::: {.column width=\"35%\"}\n\n$x_1 = (x_{1,1}, x_{1,2}) = (173.58 ,200.14)$  \n\n$y_1 =$ healthy\n\n$\\vdots$\n\n$x_{44} = (x_{44,1}, x_{44,2}) = (157.06, 122.96)$  \n\n$y_{44} =$ malnourished\n\n$\\vdots$\n\n$x_{90} = (x_{90,1}, x_{90,2}) = (163.48, 164.98)$ \n\n$y_{90} =$ injured\n\n:::\n\n::::\n\nShe can use this data to train a classifier, and then use it to predict the health status of new, unlabeled seals given their weight and length. \n\n::: {#5161b7ce .cell execution_count=9}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-10-output-1.png){width=789 height=390}\n:::\n:::\n\n\n## Unsupervised vs. Supervised Learning\n\n**Supervised learning:** each observation has predictors associated to a response variable:\n$$\\text{training set} = \\{(x_1, y_1), ..., (x_n, y_n)\\}$$\n\nwhere each $x_i = (x_{i1}, ..., x_{ip})$ is a vector with $p$ predictors and $y_i$ is the response to $x_i$. \n\n**Unsupervised learning:** each observation only has **features**, no response variable.\n\nOur training set only has observations of $p$ different features:\n$$ \\text{training set} = \\{ x_1, ..., x_n\\},$$\n\nwhere each $x_i = (x_{i1}, ..., x_{ip})$ is a vector with $p$ features. There's no reponse variable $Y$. \n\nIn unsupervised learning problems, we seek to understand the relationships between the variables or between the observations. \n\n### Example\n\n\nAmanda records **dive depth** and **dive duration** for a large number of seals, but has no prior labels or categories in mind. She wants to know: *are there distinct foraging strategies among these seals?* Her data looks like this:\n\n:::: {.columns}\n\n::: {.column width=\"55%\"}\n| Obs. | Depth (Feature 1) | Duration (Feature 2) | \n|-------------|------|------|\n| 1 | 585.29 | 39.39| \n| $\\vdots$ | $\\vdots$ |  $\\vdots$ |\n| 23 | 108.23 | 9.52 |\n| $\\vdots$ | $\\vdots$ | $\\vdots$ | \n| 41 | 324.37 | 23.2 |\n:::\n\n::: {.column width=\"10%\"}\n\\\n\n\\\n\n\\\n\n\\\n\n\\ \\ \\ \\ \\ \\ \\ \\ \\ **→**\n:::\n\n::: {.column width=\"35%\"}\n\n\\\n\n$x_1 = (x_{1,1}, x_{1,2}) = (585.29, 39.39)$  \n\n$\\vdots$\n\n$x_{23} = (x_{23,1}, x_{23,2}) = (108.23, 9.52)$  \n\n$\\vdots$\n\n$x_{41} = (x_{41,1}, x_{41,2}) = (324.37, 23.2)$ \n\n:::\n\n::::\n\nIn this case, there is no response variable $y$, Amanda lets the algorithm find structure in the data on its own.\n\n::: {#7a05a930 .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![](2_1_what_is_statistical_learning-NOTES_files/figure-html/cell-11-output-1.png){width=789 height=791}\n:::\n:::\n\n\nThe top plot shows what Amanda starts with: just measurements, no categories. The bottom plot shows the structure the algorithm uncovers, which Amanda interprets as distinct **foraging strategies**.\n\n::: {.callout-tip}\n## Check-in\nWhat is the key difference between the classification and clustering examples above?\n:::\n\n\n## Recap\n\nWhat we covered today:\n\n- The idea of estimating a function $f$ using observed data\n- Inference and prediction\n- Training set = observations used to fit/train a model\n- Predictors + response variable & their math notation\n- Parametric vs. non parametric\n- Regression vs. classification\n- Supervised vs. unsupervised learning\n\nNext class: assessing model accuracy\n\n",
    "supporting": [
      "2_1_what_is_statistical_learning-NOTES_files"
    ],
    "filters": [],
    "includes": {}
  }
}